import type { Product, Review } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Smartphone Pro X',
    description: 'Latest model with AI camera and long battery life.',
    longDescription: 'Experience the future with Smartphone Pro X. Featuring a stunning 6.7-inch OLED display, the new A17 Bionic chip, and an advanced triple-camera system with LiDAR. Enjoy all-day battery life and 5G connectivity. Perfect for professionals and tech enthusiasts.',
    price: 799.99,
    originalPrice: 899.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smartphone tech',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    category: 'Mobiles', // Changed from Electronics to Mobiles
    brand: 'TechCorp',
    rating: 4.5,
    reviewsCount: 120,
    stock: 50,
    tags: ['smartphone', 'mobile', 'tech', 'electronics'],
    specifications: {
      Screen: '6.7" OLED',
      Processor: 'A17 Bionic',
      RAM: '8GB',
      Storage: '256GB',
      Camera: '48MP Triple-Lens',
    },
  },
  {
    id: '2',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immersive sound quality with active noise cancellation.',
    longDescription: 'Dive into pure sound with these premium wireless headphones. Featuring industry-leading noise cancellation, crystal-clear audio, and up to 30 hours of battery life. Comfortable over-ear design for extended listening sessions.',
    price: 249.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'headphones audio',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    category: 'Electronics',
    brand: 'AudioPhonic',
    rating: 4.8,
    reviewsCount: 250,
    stock: 100,
    tags: ['audio', 'headphones', 'music', 'electronics'],
    specifications: {
      Type: 'Over-ear',
      Connectivity: 'Bluetooth 5.2',
      BatteryLife: '30 hours',
      NoiseCancellation: 'Active',
    },
  },
  {
    id: '3',
    name: 'Ultra HD Smart TV 55"',
    description: 'Stunning 4K resolution with smart features.',
    longDescription: 'Transform your viewing experience with this 55-inch 4K Ultra HD Smart TV. Enjoy vibrant colors, sharp details, and access to all your favorite streaming apps. Slim design that complements any living space.',
    price: 499.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smart tv',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    category: 'Electronics',
    brand: 'VisionMax',
    rating: 4.6,
    reviewsCount: 95,
    stock: 30,
    tags: ['tv', 'home entertainment', 'smart tv', 'electronics'],
     specifications: {
      ScreenSize: '55 inch',
      Resolution: '4K Ultra HD',
      SmartFeatures: 'Yes, WebOS',
      HDR: 'HDR10, Dolby Vision',
    },
  },
  {
    id: '4',
    name: 'Espresso Coffee Machine',
    description: 'Barista-quality espresso at home.',
    longDescription: 'Start your day right with the perfect espresso. This machine features a 15-bar pressure pump, milk frother, and easy-to-use controls. Durable stainless steel construction.',
    price: 199.50,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'coffee machine',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    category: 'Appliances',
    brand: 'CafeHome',
    rating: 4.3,
    reviewsCount: 75,
    stock: 60,
    tags: ['coffee', 'kitchen', 'appliances', 'home appliances'],
    specifications: {
      PumpPressure: '15 Bar',
      Material: 'Stainless Steel',
      MilkFrother: 'Yes',
      WaterTank: '1.5L',
    },
  },
  {
    id: '5',
    name: 'Men\'s Classic Leather Wallet',
    description: 'Genuine leather wallet with multiple compartments.',
    longDescription: 'A timeless accessory, this classic wallet is crafted from genuine leather. It features multiple card slots, a bill compartment, and an ID window. Slim and durable design.',
    price: 45.00,
    originalPrice: 55.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'leather wallet',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    category: 'Fashion',
    brand: 'GentStyle',
    rating: 4.7,
    reviewsCount: 150,
    stock: 200,
    tags: ['wallet', 'mens fashion', 'accessories', 'fashion'],
    specifications: {
      Material: 'Genuine Leather',
      Color: 'Black',
      CardSlots: '8',
      IDWindow: 'Yes',
    },
  },
  {
    id: '6',
    name: 'Yoga Mat Premium',
    description: 'Eco-friendly, non-slip yoga mat for all practices.',
    longDescription: 'Enhance your yoga practice with this premium, eco-friendly mat. Made from natural tree rubber, it offers excellent grip and cushioning. Lightweight and easy to carry.',
    price: 39.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'yoga mat',
    images: [
      'https://placehold.co/600x600.png',
    ],
    category: 'Sports & Outdoors',
    brand: 'ZenFlow',
    rating: 4.9,
    reviewsCount: 300,
    stock: 120,
    tags: ['yoga', 'fitness', 'sports'],
    specifications: {
      Material: 'Natural Tree Rubber',
      Thickness: '5mm',
      Dimensions: '72" x 24"',
      EcoFriendly: 'Yes',
    },
  },
  // New Products
  {
    id: '7',
    name: 'Organic Apples (1kg)',
    description: 'Fresh and juicy organic apples, perfect for snacking.',
    longDescription: 'Enjoy the crisp taste of our certified organic apples. Grown without synthetic pesticides or fertilizers, these apples are a healthy and delicious choice for the whole family. Each pack contains approximately 1kg.',
    price: 4.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'apples grocery',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'FarmFresh',
    rating: 4.6,
    reviewsCount: 45,
    stock: 150,
    tags: ['grocery', 'fruits', 'organic', 'healthy'],
    specifications: {
      Weight: '1kg (approx)',
      Type: 'Organic Gala Apples',
      Origin: 'Local Farms',
    },
  },
  {
    id: '8',
    name: 'Whole Wheat Bread Loaf',
    description: 'Nutritious whole wheat bread, freshly baked.',
    longDescription: 'Our whole wheat bread is baked fresh daily using 100% whole grain flour. It\'s a great source of fiber and perfect for sandwiches or toast. No artificial preservatives.',
    price: 3.50,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'bread grocery',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'BakeryLane',
    rating: 4.4,
    reviewsCount: 30,
    stock: 80,
    tags: ['grocery', 'bakery', 'bread', 'whole wheat'],
    specifications: {
      Ingredients: 'Whole wheat flour, water, yeast, salt',
      Dietary: 'No artificial preservatives',
    },
  },
  {
    id: '9',
    name: 'Smartphone Lite Y',
    description: 'Affordable smartphone with essential features.',
    longDescription: 'The Smartphone Lite Y offers a great balance of performance and affordability. It features a 6.2-inch HD+ display, a reliable octa-core processor, and a dual-camera setup. Ideal for everyday use and staying connected.',
    price: 199.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smartphone budget',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Mobiles',
    brand: 'BudgetMobile',
    rating: 4.2,
    reviewsCount: 85,
    stock: 70,
    tags: ['smartphone', 'mobile', 'budget', 'electronics'],
    specifications: {
      Screen: '6.2" HD+ LCD',
      Processor: 'Octa-core',
      RAM: '4GB',
      Storage: '64GB',
      Camera: '13MP Dual-Lens',
    },
  },
  {
    id: '10',
    name: 'Women\'s Summer Dress',
    description: 'Light and airy floral print summer dress.',
    longDescription: 'Stay cool and stylish this summer with our beautiful floral print dress. Made from lightweight cotton, it features a flattering A-line silhouette and adjustable straps. Perfect for casual outings or beach days.',
    price: 35.99,
    originalPrice: 49.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'dress fashion',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'ChicStyle',
    rating: 4.5,
    reviewsCount: 60,
    stock: 90,
    tags: ['dress', 'womens fashion', 'summer', 'floral', 'fashion'],
    specifications: {
      Material: '100% Cotton',
      Print: 'Floral',
      Fit: 'A-line',
      Care: 'Machine washable',
    },
  },
  {
    id: '11',
    name: 'Men\'s Casual Sneakers',
    description: 'Comfortable and stylish sneakers for everyday wear.',
    longDescription: 'Step out in style with these versatile casual sneakers. Featuring a breathable canvas upper, cushioned insole, and durable rubber outsole. Perfect for pairing with jeans or shorts.',
    price: 59.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'sneakers fashion',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'UrbanStep',
    rating: 4.3,
    reviewsCount: 110,
    stock: 120,
    tags: ['sneakers', 'mens fashion', 'footwear', 'casual', 'fashion'],
    specifications: {
      UpperMaterial: 'Canvas',
      Sole: 'Rubber',
      Closure: 'Lace-up',
      Color: 'Navy Blue',
    },
  },
  {
    id: '12',
    name: 'Gaming Laptop Predator Z',
    description: 'High-performance gaming laptop with RTX graphics.',
    longDescription: 'Dominate the game with the Predator Z gaming laptop. Equipped with the latest Intel Core i7 processor, NVIDIA GeForce RTX graphics, a 144Hz display, and advanced cooling system. Ready for AAA titles and intensive multitasking.',
    price: 1499.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'laptop gaming',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'CyberPower',
    rating: 4.7,
    reviewsCount: 70,
    stock: 25,
    tags: ['laptop', 'gaming', 'pc', 'electronics'],
    specifications: {
      Processor: 'Intel Core i7 (12th Gen)',
      Graphics: 'NVIDIA GeForce RTX 3070',
      Display: '15.6" FHD 144Hz',
      RAM: '16GB DDR5',
      Storage: '1TB NVMe SSD',
    },
  },
  {
    id: '13',
    name: 'Modern Bookshelf',
    description: 'Stylish and sturdy 5-tier bookshelf for your home.',
    longDescription: 'Organize your books and display your favorite decor items with this modern 5-tier bookshelf. Made from durable engineered wood with a sleek finish, it adds a touch of elegance to any room.',
    price: 89.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'bookshelf furniture',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'DecorHome',
    rating: 4.4,
    reviewsCount: 55,
    stock: 40,
    tags: ['bookshelf', 'furniture', 'home decor', 'storage'],
    specifications: {
      Material: 'Engineered Wood',
      Tiers: '5',
      Dimensions: '70" H x 30" W x 12" D',
      Assembly: 'Required',
    },
  },
  {
    id: '14',
    name: 'Decorative Throw Pillows (Set of 2)',
    description: 'Soft and stylish throw pillows to accent your sofa or bed.',
    longDescription: 'Add a cozy and decorative touch to your living space with this set of two throw pillows. Featuring a chic geometric pattern and plush filling, they provide both comfort and style. Covers are removable and washable.',
    price: 29.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'pillows decor',
    images: ['https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'CozyLiving',
    rating: 4.6,
    reviewsCount: 90,
    stock: 75,
    tags: ['pillows', 'cushions', 'home decor', 'textiles'],
    specifications: {
      SetIncludes: '2 Pillows',
      Size: '18" x 18"',
      CoverMaterial: 'Polyester Blend',
      Filling: 'Hypoallergenic Polyester',
    },
  },
  {
    id: '15',
    name: 'Robot Vacuum Cleaner',
    description: 'Smart robot vacuum with mapping and app control.',
    longDescription: 'Keep your floors clean effortlessly with this smart robot vacuum cleaner. It features intelligent mapping, powerful suction, and can be controlled via a smartphone app or voice commands. Works on hard floors and carpets.',
    price: 279.00,
    originalPrice: 329.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'robot vacuum',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'CleanBot',
    rating: 4.5,
    reviewsCount: 115,
    stock: 35,
    tags: ['vacuum', 'robot vacuum', 'smart home', 'appliances', 'home appliances'],
    specifications: {
      Navigation: 'LIDAR Mapping',
      SuctionPower: '2500Pa',
      AppControl: 'Yes',
      BatteryLife: '120 minutes',
    },
  },
  {
    id: '16',
    name: 'Air Fryer XL',
    description: 'Large capacity air fryer for healthy, crispy meals.',
    longDescription: 'Enjoy your favorite fried foods with less oil using the Air Fryer XL. Its large 5.8-quart capacity is perfect for families. Features multiple cooking presets, digital touch screen, and easy-to-clean non-stick basket.',
    price: 99.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'air fryer',
    images: ['https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'KitchenPro',
    rating: 4.7,
    reviewsCount: 180,
    stock: 60,
    tags: ['air fryer', 'kitchen', 'cooking', 'healthy eating', 'appliances', 'home appliances'],
    specifications: {
      Capacity: '5.8 Quarts',
      Power: '1700W',
      Presets: '8 cooking modes',
      Control: 'Digital Touch Screen',
    },
  },
  {
    id: '17',
    name: 'Weekend Getaway Package: Mountain Retreat',
    description: '2-night stay for two at a scenic mountain lodge.',
    longDescription: 'Escape to the mountains with this relaxing weekend getaway package. Includes a 2-night stay for two people at a charming lodge, daily breakfast, and access to hiking trails. Enjoy breathtaking views and fresh mountain air.',
    price: 349.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'travel mountain',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Travel',
    brand: 'AdventureEscapes',
    rating: 4.8,
    reviewsCount: 40,
    stock: 10, // Travel packages often have limited availability
    tags: ['travel', 'vacation', 'getaway', 'mountains', 'leisure'],
    specifications: {
      Duration: '2 nights',
      Includes: 'Accommodation, Breakfast',
      Location: 'Serene Mountain Valley',
      Validity: '6 months from purchase',
    },
  },
  {
    id: '18',
    name: 'City Tour: Historical Landmarks',
    description: 'Guided walking tour of the city\'s most famous historical sites.',
    longDescription: 'Discover the rich history of the city with our expert-guided walking tour. Visit iconic landmarks, learn fascinating stories, and immerse yourself in the local culture. Tour lasts approximately 3 hours.',
    price: 45.00, // Price per person
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'travel city tour',
    images: ['https://placehold.co/600x600.png'],
    category: 'Travel',
    brand: 'UrbanExplorers',
    rating: 4.6,
    reviewsCount: 75,
    stock: 50, // Represents tour capacity or voucher availability
    tags: ['travel', 'city tour', 'tourism', 'historical', 'guided tour'],
    specifications: {
      Type: 'Walking Tour',
      Duration: '3 hours',
      GroupSize: 'Max 15 people',
      Language: 'English',
    },
  },
];

export const mockReviews: Review[] = [
  { id: 'r1', productId: '1', author: 'John D.', rating: 5, comment: 'Amazing phone, super fast and great camera!', date: '2023-10-01' },
  { id: 'r2', productId: '1', author: 'Jane S.', rating: 4, comment: 'Good phone, battery could be slightly better.', date: '2023-10-05' },
  { id: 'r3', productId: '2', author: 'Mike B.', rating: 5, comment: 'Best headphones I have ever owned. Noise cancellation is superb.', date: '2023-09-15' },
  { id: 'r4', productId: '2', author: 'Lisa K.', rating: 4, comment: 'Very comfortable and great sound, a bit pricey though.', date: '2023-09-20' },
  { id: 'r5', productId: '7', author: 'Sarah P.', rating: 5, comment: 'These apples are delicious and so fresh!', date: '2023-11-01' },
  { id: 'r6', productId: '8', author: 'Tom W.', rating: 4, comment: 'Good solid bread, makes great toast.', date: '2023-11-02' },
  { id: 'r7', productId: '9', author: 'Emily R.', rating: 4, comment: 'Great value for the price, does everything I need.', date: '2023-10-20' },
  { id: 'r8', productId: '10', author: 'Jessica L.', rating: 5, comment: 'Love this dress! Perfect for summer.', date: '2023-07-10' },
  { id: 'r9', productId: '12', author: 'Kevin G.', rating: 5, comment: 'Absolute beast of a laptop. Runs everything smoothly.', date: '2023-10-25' },
  { id: 'r10', productId: '15', author: 'Maria C.', rating: 4, comment: 'Robot vacuum is a lifesaver. Cleans pretty well.', date: '2023-09-30' },
  { id: 'r11', productId: '17', author: 'David K.', rating: 5, comment: 'The mountain retreat was fantastic. So peaceful.', date: '2023-08-15' },
];

export function getAllProducts(): Product[] {
  return mockProducts;
}

export function getProductById(id: string): Product | undefined {
  return mockProducts.find(product => product.id === id);
}

export function getReviewsByProductId(productId: string): Review[] {
  return mockReviews.filter(review => review.productId === productId);
}
