
import type { Product, Review } from '@/types';

export const mockProducts: Product[] = [
  // Mobiles
  {
    id: '1',
    name: 'Smartphone Pro X (TechCorp)',
    description: 'Latest model with AI camera and long battery life.',
    longDescription: 'Experience the future with Smartphone Pro X. Featuring a stunning 6.7-inch OLED display, the new A17 Bionic chip, and an advanced triple-camera system with LiDAR. Enjoy all-day battery life and 5G connectivity. Perfect for professionals and tech enthusiasts.',
    price: 64999,
    originalPrice: 72999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smartphone tech',
    images: [
      'https://placehold.co/600x600.png?text=ProX_View1',
      'https://placehold.co/600x600.png?text=ProX_View2',
      'https://placehold.co/600x600.png?text=ProX_View3',
    ],
    category: 'Mobiles',
    brand: 'TechCorp',
    rating: 4.5,
    reviewsCount: 120,
    stock: 50,
    tags: ['smartphone', 'mobile', 'tech', 'electronics'],
    specifications: { Screen: '6.7" OLED', Processor: 'A17 Bionic', RAM: '8GB', Storage: '256GB', Camera: '48MP Triple-Lens'},
  },
  {
    id: '9',
    name: 'Smartphone Lite Y (BudgetMobile)',
    description: 'Affordable smartphone with essential features.',
    longDescription: 'The Smartphone Lite Y offers a great balance of performance and affordability. It features a 6.2-inch HD+ display, a reliable octa-core processor, and a dual-camera setup. Ideal for everyday use and staying connected.',
    price: 12999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'budget smartphone',
    images: ['https://placehold.co/600x600.png?text=LiteY_View1', 'https://placehold.co/600x600.png?text=LiteY_View2'],
    category: 'Mobiles',
    brand: 'BudgetMobile',
    rating: 4.2,
    reviewsCount: 85,
    stock: 70,
    tags: ['smartphone', 'mobile', 'budget', 'electronics'],
    specifications: { Screen: '6.2" HD+ LCD', Processor: 'Octa-core', RAM: '4GB', Storage: '64GB', Camera: '13MP Dual-Lens'},
  },
  {
    id: '26',
    name: 'GalaxyPrime Ultra 24',
    description: 'Top-tier smartphone with cutting-edge technology and features.',
    longDescription: 'The GalaxyPrime Ultra 24 pushes the boundaries of mobile technology. With its dynamic AMOLED 3X display, revolutionary 200MP camera system, and the fastest processor yet, it offers an unparalleled experience. Includes S-Pen support.',
    price: 99990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'galaxy phone',
    images: ['https://placehold.co/600x600.png?text=Ultra24_1', 'https://placehold.co/600x600.png?text=Ultra24_2', 'https://placehold.co/600x600.png?text=Ultra24_3', 'https://placehold.co/600x600.png?text=Ultra24_4'],
    category: 'Mobiles',
    brand: 'Samsung',
    rating: 4.9,
    reviewsCount: 350,
    stock: 40,
    tags: ['smartphone', 'mobile', 'flagship', 'premium', 'tech', 'samsung'],
    specifications: { Screen: '6.8" Dynamic AMOLED 3X', Processor: 'Snapdragon Gen 4', RAM: '12GB', Storage: '512GB', Camera: '200MP Quad-Camera', Battery: '5000mAh'},
  },
  {
    id: '36',
    name: 'iFruit Phone 16 Pro',
    description: 'The ultimate iFruit experience with ProMotion display and cinematic mode.',
    longDescription: 'Discover the iFruit Phone 16 Pro, featuring a super-responsive ProMotion display, A18 Pro chip for breakthrough performance, and an advanced camera system for incredible photos and videos in any light. Cinematic mode now in 4K HDR.',
    price: 129900,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'ifruit phone',
    images: ['https://placehold.co/600x600.png?text=iFruit16P_1', 'https://placehold.co/600x600.png?text=iFruit16P_2', 'https://placehold.co/600x600.png?text=iFruit16P_3'],
    category: 'Mobiles',
    brand: 'Apple',
    rating: 4.8,
    reviewsCount: 450,
    stock: 30,
    tags: ['apple', 'ifruit', 'smartphone', 'premium', 'ios'],
    specifications: { Display: '6.1" Super Retina XDR', Chip: 'A18 Pro', Camera: '48MP Main, ProRAW', Storage: '256GB', OS: 'iFruitOS 18'},
  },
  {
    id: '37',
    name: 'Pixel Perfect 9',
    description: 'The smarts of Googel in a powerful, helpful phone.',
    longDescription: 'Pixel Perfect 9 delivers an amazing camera experience powered by Googel AI, the Tensor G4 chip for speed and security, and features that adapt to you. Enjoy all-day battery and exclusive Pixel features.',
    price: 74990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'pixel phone',
    images: ['https://placehold.co/600x600.png?text=Pixel9_1', 'https://placehold.co/600x600.png?text=Pixel9_2'],
    category: 'Mobiles',
    brand: 'Google',
    rating: 4.7,
    reviewsCount: 320,
    stock: 45,
    tags: ['google', 'pixel', 'smartphone', 'android', 'ai camera'],
    specifications: { Display: '6.3" OLED, 120Hz', Chip: 'Tensor G4', Camera: '50MP Advanced AI', Storage: '128GB', OS: 'Android 15'},
  },
  {
    id: '38',
    name: 'OnePlus Ace 12',
    description: 'Flagship performance with incredibly fast charging.',
    longDescription: 'The OnePlus Ace 12 combines speed and power with a sleek design. Featuring a 120Hz Fluid AMOLED display, the latest Snapdragon processor, and 150W SUPERVOOC charging. Hasselblad camera for stunning photos.',
    price: 54999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'oneplus phone',
    images: ['https://placehold.co/600x600.png?text=Ace12_1', 'https://placehold.co/600x600.png?text=Ace12_2'],
    category: 'Mobiles',
    brand: 'OnePlus',
    rating: 4.6,
    reviewsCount: 280,
    stock: 50,
    tags: ['oneplus', 'smartphone', 'fast charging', 'android'],
    specifications: { Display: '6.7" Fluid AMOLED, 120Hz', Processor: 'Snapdragon 8 Gen 3', Camera: '50MP Hasselblad', Charging: '150W SUPERVOOC', RAM: '12GB'},
  },
  {
    id: '39',
    name: 'XiaoMi HyperPhone 14',
    description: 'Cutting-edge features at an unbeatable price point.',
    longDescription: 'XiaoMi HyperPhone 14 offers a premium experience without the premium price. Boasting a vibrant AMOLED display, a versatile 108MP camera system, and powerful performance for gaming and multitasking. Long-lasting battery with fast charging.',
    price: 32999,
    originalPrice: 35999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'xiaomi phone',
    images: ['https://placehold.co/600x600.png?text=Hyper14_1', 'https://placehold.co/600x600.png?text=Hyper14_2', 'https://placehold.co/600x600.png?text=Hyper14_3'],
    category: 'Mobiles',
    brand: 'Xiaomi',
    rating: 4.5,
    reviewsCount: 550,
    stock: 60,
    tags: ['xiaomi', 'smartphone', 'value', 'android', 'miui'],
    specifications: { Display: '6.67" AMOLED, 120Hz', Camera: '108MP Triple', Processor: 'Snapdragon 7+ Gen 2', Battery: '5000mAh, 67W Turbo Charging', RAM: '8GB'},
  },
  {
    id: '40',
    name: 'RealChampion GT Neo 7',
    description: 'Performance-driven smartphone for gaming enthusiasts.',
    longDescription: 'The RealChampion GT Neo 7 is built for speed. With its powerful Dimensity processor, dedicated gaming mode, and ultra-smooth display, it offers an immersive gaming experience. Stylish design with vapor chamber cooling.',
    price: 28999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'realme phone',
    images: ['https://placehold.co/600x600.png?text=GTNeo7_1'],
    category: 'Mobiles',
    brand: 'Realme',
    rating: 4.4,
    reviewsCount: 210,
    stock: 55,
    tags: ['realme', 'smartphone', 'gaming', 'performance', 'android'],
    specifications: { Display: '6.74" AMOLED, 144Hz', Processor: 'Dimensity 9000+', RAM: '12GB', Storage: '256GB', Cooling: 'Vapor Chamber'},
  },
  {
    id: '41',
    name: 'OPPO Find X8 Pro',
    description: 'Masterpiece of design and camera innovation.',
    longDescription: 'The OPPO Find X8 Pro is a testament to aesthetic design and photographic excellence. Featuring a unique ceramic body, Hasselblad camera co-engineered system, and a stunning LTPO AMOLED display. Experience pro-level photography.',
    price: 89990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'oppo phone',
    images: ['https://placehold.co/600x600.png?text=FindX8P_1', 'https://placehold.co/600x600.png?text=FindX8P_2'],
    category: 'Mobiles',
    brand: 'OPPO',
    rating: 4.7,
    reviewsCount: 190,
    stock: 35,
    tags: ['oppo', 'smartphone', 'camera', 'design', 'premium'],
    specifications: { Display: '6.8" LTPO AMOLED, 120Hz', Camera: 'Dual 50MP Hasselblad', Material: 'Ceramic', Processor: 'Snapdragon 8 Gen 3', OS: 'ColorOS'},
  },

  // Electronics
  {
    id: '2',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immersive sound quality with active noise cancellation.',
    longDescription: 'Dive into pure sound with these premium wireless headphones. Featuring industry-leading noise cancellation, crystal-clear audio, and up to 30 hours of battery life. Comfortable over-ear design for extended listening sessions.',
    price: 19999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'headphones noise cancelling',
    images: ['https://placehold.co/600x600.png?text=Headphones_1', 'https://placehold.co/600x600.png?text=Headphones_2'],
    category: 'Electronics',
    brand: 'AudioPhonic',
    rating: 4.8,
    reviewsCount: 250,
    stock: 100,
    tags: ['audio', 'headphones', 'music', 'electronics'],
    specifications: { Type: 'Over-ear', Connectivity: 'Bluetooth 5.2', BatteryLife: '30 hours', NoiseCancellation: 'Active'},
  },
  {
    id: '3',
    name: 'Ultra HD Smart TV 55"',
    description: 'Stunning 4K resolution with smart features.',
    longDescription: 'Transform your viewing experience with this 55-inch 4K Ultra HD Smart TV. Enjoy vibrant colors, sharp details, and access to all your favorite streaming apps. Slim design that complements any living space.',
    price: 44990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smart tv',
    images: ['https://placehold.co/600x600.png?text=TV55_1', 'https://placehold.co/600x600.png?text=TV55_2'],
    category: 'Electronics',
    brand: 'VisionMax',
    rating: 4.6,
    reviewsCount: 95,
    stock: 30,
    tags: ['tv', 'home entertainment', 'smart tv', 'electronics'],
    specifications: { ScreenSize: '55 inch', Resolution: '4K Ultra HD', SmartFeatures: 'Yes, WebOS', HDR: 'HDR10, Dolby Vision'},
  },
  {
    id: '12',
    name: 'Gaming Laptop Predator Z',
    description: 'High-performance gaming laptop with RTX graphics.',
    longDescription: 'Dominate the game with the Predator Z gaming laptop. Equipped with the latest Intel Core i7 processor, NVIDIA GeForce RTX graphics, a 144Hz display, and advanced cooling system. Ready for AAA titles and intensive multitasking.',
    price: 119990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'gaming laptop',
    images: ['https://placehold.co/600x600.png?text=Laptop_1', 'https://placehold.co/600x600.png?text=Laptop_2', 'https://placehold.co/600x600.png?text=Laptop_3'],
    category: 'Electronics',
    brand: 'CyberPower',
    rating: 4.7,
    reviewsCount: 70,
    stock: 25,
    tags: ['laptops', 'gaming', 'pc', 'electronics'],
    specifications: { Processor: 'Intel Core i7 (12th Gen)', Graphics: 'NVIDIA GeForce RTX 3070', Display: '15.6" FHD 144Hz', RAM: '16GB DDR5', Storage: '1TB NVMe SSD'},
  },
  {
    id: '20',
    name: 'Bluetooth Speaker Portable',
    description: 'Compact and powerful portable Bluetooth speaker.',
    longDescription: 'Take your music anywhere with this portable Bluetooth speaker. It offers rich sound, deep bass, and a rugged waterproof design. Up to 12 hours of playtime on a single charge.',
    price: 3499,
    originalPrice: 4999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'bluetooth speaker',
    images: ['https://placehold.co/600x600.png?text=Speaker_1', 'https://placehold.co/600x600.png?text=Speaker_2'],
    category: 'Electronics',
    brand: 'SoundGo',
    rating: 4.5,
    reviewsCount: 150,
    stock: 80,
    tags: ['audio', 'speaker', 'bluetooth', 'portable', 'electronics'],
    specifications: { Connectivity: 'Bluetooth 5.0', Playtime: '12 hours', Waterproof: 'IPX7', Power: '10W'},
  },
  {
    id: '28',
    name: 'Smartwatch Series 8',
    description: 'Advanced smartwatch with health tracking and GPS.',
    longDescription: 'Stay connected and track your health with the Smartwatch Series 8. Features a bright always-on display, ECG, blood oxygen monitoring, GPS, and cellular connectivity options. Water-resistant and customizable.',
    price: 29990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smart watch',
    images: ['https://placehold.co/600x600.png?text=Watch8_1', 'https://placehold.co/600x600.png?text=Watch8_2', 'https://placehold.co/600x600.png?text=Watch8_3'],
    category: 'Electronics',
    brand: 'ConnectWear',
    rating: 4.7,
    reviewsCount: 180,
    stock: 70,
    tags: ['smartwatch', 'wearable', 'health', 'fitness', 'electronics'],
    specifications: { Display: 'Always-On Retina', HealthSensors: 'ECG, SpO2, Heart Rate', GPS: 'Built-in', WaterResistance: '50 meters'},
  },
  {
    id: '32',
    name: 'Professional DSLR Camera Kit',
    description: 'Full-frame DSLR camera with 24-70mm lens kit.',
    longDescription: 'Capture stunning professional-quality images and videos with this full-frame DSLR camera. The kit includes a versatile 24-70mm f/2.8 lens, offering exceptional sharpness and low-light performance. Ideal for enthusiasts and professionals.',
    price: 189990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'dslr camera',
    images: ['https://placehold.co/600x600.png?text=DSLR_1', 'https://placehold.co/600x600.png?text=DSLR_2', 'https://placehold.co/600x600.png?text=DSLR_3'],
    category: 'Electronics',
    brand: 'PhotoPro',
    rating: 4.8,
    reviewsCount: 110,
    stock: 15,
    tags: ['cameras', 'dslr', 'photography', 'electronics', 'professional'],
    specifications: { Sensor: 'Full-Frame CMOS', Megapixels: '30.4 MP', LensIncluded: '24-70mm f/2.8', Video: '4K UHD', ISO: '100-32000 (expandable)'},
  },
  {
    id: '42',
    name: 'UltraBook Slim Pro',
    description: 'Lightweight and powerful ultrabook for productivity on the go.',
    longDescription: 'The UltraBook Slim Pro is designed for professionals who need portability and performance. It features a stunning QHD display, long battery life, and a sleek aluminum chassis. Weighs just 1.1 kg.',
    price: 98990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'ultrabook laptop',
    images: ['https://placehold.co/600x600.png?text=UltraBook_1', 'https://placehold.co/600x600.png?text=UltraBook_2'],
    category: 'Electronics',
    brand: 'LapTech',
    rating: 4.7,
    reviewsCount: 90,
    stock: 40,
    tags: ['laptops', 'ultrabook', 'business', 'portable', 'electronics'],
    specifications: { Display: '14" QHD IPS', Processor: 'Intel Core i7 (13th Gen)', RAM: '16GB LPDDR5', Storage: '1TB PCIe SSD', Weight: '1.1 kg'},
  },
  {
    id: '43',
    name: 'OLED Smart TV 65" Cinema Edition',
    description: 'Immersive 65-inch OLED TV with cinematic sound and picture.',
    longDescription: 'Experience movies like never before with the 65" OLED Smart TV Cinema Edition. Perfect blacks, infinite contrast, and vibrant colors combined with Dolby Atmos sound create a true cinematic experience in your home.',
    price: 149990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'oled tv',
    images: ['https://placehold.co/600x600.png?text=OLEDTV_1', 'https://placehold.co/600x600.png?text=OLEDTV_2'],
    category: 'Electronics',
    brand: 'CineView',
    rating: 4.9,
    reviewsCount: 150,
    stock: 20,
    tags: ['tvs', 'oled', 'smart tv', 'home theater', 'electronics'],
    specifications: { ScreenSize: '65 inch', PanelType: 'OLED', Resolution: '4K Ultra HD', Sound: 'Dolby Atmos', SmartPlatform: 'Android TV'},
  },
  {
    id: '44',
    name: 'True Wireless Earbuds Elite',
    description: 'Premium true wireless earbuds with adaptive noise cancellation.',
    longDescription: 'The True Wireless Earbuds Elite offer superior sound quality, adaptive noise cancellation that adjusts to your surroundings, and a comfortable, secure fit. Long battery life with wireless charging case.',
    price: 12999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'wireless earbuds',
    images: ['https://placehold.co/600x600.png?text=EarbudsElite_1'],
    category: 'Electronics',
    brand: 'AudioPhonic',
    rating: 4.6,
    reviewsCount: 220,
    stock: 120,
    tags: ['audio', 'earbuds', 'true wireless', 'noise cancelling', 'electronics'],
    specifications: { Connectivity: 'Bluetooth 5.3', ANC: 'Adaptive', Battery: '8 hrs (earbuds), 32 hrs (total)', WirelessCharging: 'Yes'},
  },
  {
    id: '45',
    name: 'Mirrorless Camera Alpha One',
    description: 'Professional-grade mirrorless camera with advanced autofocus.',
    longDescription: 'The Alpha One mirrorless camera delivers breathtaking image quality and unmatched autofocus performance. Featuring a high-resolution full-frame sensor, 8K video recording, and robust build quality. Ideal for professionals.',
    price: 279990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'mirrorless camera',
    images: ['https://placehold.co/600x600.png?text=AlphaOne_1', 'https://placehold.co/600x600.png?text=AlphaOne_2'],
    category: 'Electronics',
    brand: 'SonyAlpha',
    rating: 4.9,
    reviewsCount: 95,
    stock: 10,
    tags: ['cameras', 'mirrorless', 'professional', 'photography', 'electronics'],
    specifications: { Sensor: '61MP Full-Frame Exmor RS', Video: '8K 30p', AFPoints: '759 phase-detection', IBIS: '5-axis', Viewfinder: '9.44M-dot OLED'},
  },
  {
    id: '46',
    name: 'NextGen Gaming Console X',
    description: 'Powerful next-generation gaming console for immersive experiences.',
    longDescription: 'Experience the future of gaming with the NextGen Console X. Lightning-fast load times, stunning 4K graphics at 120fps, and a vast library of exclusive games. Includes innovative haptic feedback controller.',
    price: 49990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'gaming console',
    images: ['https://placehold.co/600x600.png?text=ConsoleX_1', 'https://placehold.co/600x600.png?text=ConsoleX_2'],
    category: 'Electronics',
    brand: 'GameSphere',
    rating: 4.8,
    reviewsCount: 600,
    stock: 50,
    tags: ['gaming', 'console', 'nextgen', 'entertainment', 'electronics'],
    specifications: { Resolution: 'Up to 8K', Framerate: 'Up to 120fps', Storage: '1TB Custom NVMe SSD', Controller: 'Haptic Feedback, Adaptive Triggers'},
  },
  {
    id: '47',
    name: 'Mechanical Gaming Keyboard RGB',
    description: 'RGB backlit mechanical keyboard with customizable switches.',
    longDescription: 'Elevate your gaming setup with this RGB mechanical keyboard. Features durable mechanical switches (choice of Red, Blue, Brown), customizable per-key RGB lighting, and a dedicated media control wheel. Aircraft-grade aluminum frame.',
    price: 8999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'gaming keyboard',
    images: ['https://placehold.co/600x600.png?text=KeyboardRGB_1'],
    category: 'Electronics',
    brand: 'ClickMaster',
    rating: 4.7,
    reviewsCount: 180,
    stock: 70,
    tags: ['computer accessories', 'keyboard', 'gaming', 'mechanical', 'rgb', 'electronics'],
    specifications: { SwitchType: 'Mechanical (Red/Blue/Brown options)', Backlighting: 'Per-key RGB', Connectivity: 'USB-C Wired', Material: 'Aluminum Frame'},
  },

  // Fashion
  {
    id: '5',
    name: 'Men\'s Classic Leather Wallet',
    description: 'Genuine leather wallet with multiple compartments.',
    longDescription: 'A timeless accessory, this classic wallet is crafted from genuine leather. It features multiple card slots, a bill compartment, and an ID window. Slim and durable design.',
    price: 1999,
    originalPrice: 2499,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'leather wallet',
    images: ['https://placehold.co/600x600.png?text=Wallet_1', 'https://placehold.co/600x600.png?text=Wallet_2'],
    category: 'Fashion',
    brand: 'GentStyle',
    rating: 4.7,
    reviewsCount: 150,
    stock: 200,
    tags: ['men\'s wear', 'accessories', 'wallet', 'leather', 'fashion'],
    specifications: { Material: 'Genuine Leather', Color: 'Black', CardSlots: '8', IDWindow: 'Yes'},
  },
  {
    id: '10',
    name: 'Women\'s Summer Dress (Floral)',
    description: 'Light and airy floral print summer dress.',
    longDescription: 'Stay cool and stylish this summer with our beautiful floral print dress. Made from lightweight cotton, it features a flattering A-line silhouette and adjustable straps. Perfect for casual outings or beach days.',
    price: 1499,
    originalPrice: 1999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'floral dress',
    images: ['https://placehold.co/600x600.png?text=DressFloral_1', 'https://placehold.co/600x600.png?text=DressFloral_2'],
    category: 'Fashion',
    brand: 'ChicStyle',
    rating: 4.5,
    reviewsCount: 60,
    stock: 90,
    tags: ['women\'s wear', 'dress', 'summer', 'floral', 'fashion'],
    specifications: { Material: '100% Cotton', Print: 'Floral', Fit: 'A-line', Care: 'Machine washable'},
  },
  {
    id: '11',
    name: 'Men\'s Casual Sneakers',
    description: 'Comfortable and stylish sneakers for everyday wear.',
    longDescription: 'Step out in style with these versatile casual sneakers. Featuring a breathable canvas upper, cushioned insole, and durable rubber outsole. Perfect for pairing with jeans or shorts.',
    price: 2499,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'men sneakers',
    images: ['https://placehold.co/600x600.png?text=Sneakers_1', 'https://placehold.co/600x600.png?text=Sneakers_2'],
    category: 'Fashion',
    brand: 'UrbanStep',
    rating: 4.3,
    reviewsCount: 110,
    stock: 120,
    tags: ['footwear', 'men\'s wear', 'sneakers', 'casual', 'fashion'],
    specifications: { UpperMaterial: 'Canvas', Sole: 'Rubber', Closure: 'Lace-up', Color: 'Navy Blue'},
  },
  {
    id: '21',
    name: 'Men\'s Running Shoes',
    description: 'Lightweight and breathable running shoes for men.',
    longDescription: 'Achieve your personal best with these lightweight running shoes. Designed for comfort and performance, they feature a breathable mesh upper, responsive cushioning, and durable outsole for excellent traction.',
    price: 3990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'running shoes',
    images: ['https://placehold.co/600x600.png?text=RunShoes_1', 'https://placehold.co/600x600.png?text=RunShoes_2', 'https://placehold.co/600x600.png?text=RunShoes_3'],
    category: 'Fashion',
    brand: 'RunFlex',
    rating: 4.6,
    reviewsCount: 130,
    stock: 100,
    tags: ['footwear', 'men\'s wear', 'sportswear', 'running shoes', 'fashion'],
    specifications: { Type: 'Neutral', Weight: '250g (Size 9)', Drop: '8mm', Use: 'Road Running'},
  },
  {
    id: '27',
    name: 'Women\'s Elegant Evening Gown',
    description: 'Stunning floor-length evening gown for special occasions.',
    longDescription: 'Make a grand entrance with this elegant evening gown. Crafted from luxurious satin, it features a flattering silhouette, intricate beadwork, and a subtle train. Perfect for galas, weddings, or formal events.',
    price: 14990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'evening gown',
    images: ['https://placehold.co/600x600.png?text=Gown_1', 'https://placehold.co/600x600.png?text=Gown_2'],
    category: 'Fashion',
    brand: 'Elegance Couture',
    rating: 4.8,
    reviewsCount: 45,
    stock: 30,
    tags: ['women\'s wear', 'evening gown', 'formal wear', 'dress', 'fashion'],
    specifications: { Material: 'Satin, Beading', Length: 'Floor-length', Color: 'Midnight Blue', Sizes: 'XS, S, M, L, XL'},
  },
  {
    id: '33',
    name: 'Luxury Leather Handbag',
    description: 'Chic and spacious leather handbag for women.',
    longDescription: 'This luxury handbag is crafted from premium Italian leather, offering both style and durability. It features a spacious interior, multiple pockets, and elegant gold-tone hardware. A timeless piece for any wardrobe.',
    price: 17999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'leather handbag',
    images: ['https://placehold.co/600x600.png?text=Handbag_1', 'https://placehold.co/600x600.png?text=Handbag_2'],
    category: 'Fashion',
    brand: 'BellaDonna',
    rating: 4.7,
    reviewsCount: 80,
    stock: 40,
    tags: ['bags & luggage', 'women\'s wear', 'handbag', 'leather', 'accessories', 'luxury', 'fashion'],
    specifications: { Material: 'Italian Leather', Color: 'Cognac', Dimensions: '12" H x 15" W x 6" D', Hardware: 'Gold-tone'},
  },
  {
    id: '48',
    name: 'Men\'s Slim Fit Chinos',
    description: 'Versatile slim fit chinos for smart-casual look.',
    longDescription: 'Crafted from comfortable stretch cotton, these slim fit chinos are a wardrobe staple. Perfect for both office and weekend wear, they offer a modern silhouette and all-day comfort.',
    price: 1799,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'men chinos',
    images: ['https://placehold.co/600x600.png?text=Chinos_1', 'https://placehold.co/600x600.png?text=Chinos_2'],
    category: 'Fashion',
    brand: 'ModernMan',
    rating: 4.5,
    reviewsCount: 120,
    stock: 150,
    tags: ['men\'s wear', 'pants', 'chinos', 'smart casual', 'fashion'],
    specifications: { Material: '98% Cotton, 2% Elastane', Fit: 'Slim', Colors: 'Khaki, Navy, Grey'},
  },
  {
    id: '49',
    name: 'Women\'s Knit Cardigan',
    description: 'Cozy knit cardigan, perfect for layering.',
    longDescription: 'This soft knit cardigan is an essential layering piece for cooler weather. It features an open front, long sleeves, and a relaxed fit. Available in various colors to match any outfit.',
    price: 1299,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'knit cardigan',
    images: ['https://placehold.co/600x600.png?text=Cardigan_1'],
    category: 'Fashion',
    brand: 'CozyKnits',
    rating: 4.6,
    reviewsCount: 95,
    stock: 110,
    tags: ['women\'s wear', 'cardigan', 'knitwear', 'sweater', 'fashion'],
    specifications: { Material: 'Acrylic Blend', Style: 'Open Front', Sleeves: 'Long', Sizes: 'S, M, L, XL'},
  },
  {
    id: '50',
    name: 'Kids\' Graphic Tee (Dinosaur Print)',
    description: 'Fun and comfortable graphic t-shirt for kids.',
    longDescription: 'Let your little one roar in style with this adorable dinosaur print t-shirt. Made from soft, breathable cotton, it\'s perfect for everyday play and adventures. Durable and easy to wash.',
    price: 599,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'kids tee',
    images: ['https://placehold.co/600x600.png?text=KidsTee_1'],
    category: 'Fashion',
    brand: 'TinyExplorer',
    rating: 4.8,
    reviewsCount: 70,
    stock: 200,
    tags: ['kids\' wear', 't-shirt', 'graphic tee', 'children', 'fashion'],
    specifications: { Material: '100% Cotton', Print: 'Dinosaur Graphic', AgeGroup: '2-8 years'},
  },
  {
    id: '51',
    name: 'Unisex Leather Ankle Boots',
    description: 'Stylish and durable leather ankle boots for all seasons.',
    longDescription: 'These versatile ankle boots are crafted from genuine leather and feature a rugged yet refined design. With a comfortable cushioned insole and slip-resistant outsole, they are perfect for everyday wear.',
    price: 4990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'leather boots',
    images: ['https://placehold.co/600x600.png?text=AnkleBoots_1', 'https://placehold.co/600x600.png?text=AnkleBoots_2'],
    category: 'Fashion',
    brand: 'UrbanTrekker',
    rating: 4.7,
    reviewsCount: 150,
    stock: 80,
    tags: ['footwear', 'boots', 'leather', 'unisex', 'fashion'],
    specifications: { Material: 'Genuine Leather', Sole: 'Rubber', Closure: 'Lace-up/Side Zip', Colors: 'Black, Brown'},
  },
  {
    id: '52',
    name: 'Classic Chronograph Watch',
    description: 'Elegant chronograph watch with stainless steel bracelet.',
    longDescription: 'A sophisticated timepiece for any occasion. This classic chronograph watch features a precise quartz movement, a durable stainless steel case and bracelet, and a striking blue dial. Water-resistant up to 50m.',
    price: 8999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'chrono watch',
    images: ['https://placehold.co/600x600.png?text=WatchChrono_1', 'https://placehold.co/600x600.png?text=WatchChrono_2'],
    category: 'Fashion',
    brand: 'TimelessPieces',
    rating: 4.6,
    reviewsCount: 110,
    stock: 60,
    tags: ['watches', 'chronograph', 'accessories', 'men\'s wear', 'women\'s wear', 'fashion'],
    specifications: { Movement: 'Quartz Chronograph', CaseMaterial: 'Stainless Steel', WaterResistance: '5 ATM', DialColor: 'Blue'},
  },
  {
    id: '53',
    name: 'Expandable Hardshell Luggage Set (3-Piece)',
    description: 'Durable and lightweight hardshell luggage set for all your travels.',
    longDescription: 'Travel with confidence with this 3-piece hardshell luggage set. Includes carry-on, medium, and large suitcases, all featuring expandable capacity, 360-degree spinner wheels, and TSA-approved locks. Scratch-resistant ABS material.',
    price: 9990,
    originalPrice: 12990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'luggage set',
    images: ['https://placehold.co/600x600.png?text=LuggageSet_1', 'https://placehold.co/600x600.png?text=LuggageSet_2'],
    category: 'Fashion', // Also Travel
    brand: 'VoyagerElite',
    rating: 4.5,
    reviewsCount: 200,
    stock: 70,
    tags: ['bags & luggage', 'travel', 'suitcases', 'hardshell', 'fashion'],
    specifications: { Material: 'ABS Hardshell', SetIncludes: 'Carry-on, Medium, Large', Wheels: '360° Spinner', Lock: 'TSA-Approved'},
  },

  // Home & Decor
  {
    id: '13',
    name: 'Modern Bookshelf',
    description: 'Stylish and sturdy 5-tier bookshelf for your home.',
    longDescription: 'Organize your books and display your favorite decor items with this modern 5-tier bookshelf. Made from durable engineered wood with a sleek finish, it adds a touch of elegance to any room.',
    price: 4999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'modern bookshelf',
    images: ['https://placehold.co/600x600.png?text=Bookshelf_1', 'https://placehold.co/600x600.png?text=Bookshelf_2'],
    category: 'Home & Decor',
    brand: 'DecorHome',
    rating: 4.4,
    reviewsCount: 55,
    stock: 40,
    tags: ['furniture', 'bookshelf', 'home decor', 'storage'],
    specifications: { Material: 'Engineered Wood', Tiers: '5', Dimensions: '70" H x 30" W x 12" D', Assembly: 'Required'},
  },
  {
    id: '14',
    name: 'Decorative Throw Pillows (Set of 2)',
    description: 'Soft and stylish throw pillows to accent your sofa or bed.',
    longDescription: 'Add a cozy and decorative touch to your living space with this set of two throw pillows. Featuring a chic geometric pattern and plush filling, they provide both comfort and style. Covers are removable and washable.',
    price: 999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'throw pillows',
    images: ['https://placehold.co/600x600.png?text=Pillows_1'],
    category: 'Home & Decor',
    brand: 'CozyLiving',
    rating: 4.6,
    reviewsCount: 90,
    stock: 75,
    tags: ['home decor', 'pillows', 'cushions', 'textiles'],
    specifications: { SetIncludes: '2 Pillows', Size: '18" x 18"', CoverMaterial: 'Polyester Blend', Filling: 'Hypoallergenic Polyester'},
  },
  {
    id: '22',
    name: 'Ceramic Dinnerware Set (16-Piece)',
    description: 'Elegant ceramic dinnerware set for 4 people.',
    longDescription: 'Elevate your dining experience with this beautiful 16-piece ceramic dinnerware set. Includes dinner plates, salad plates, bowls, and mugs for four. Microwave and dishwasher safe. Available in multiple colors.',
    price: 3990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'dinnerware set',
    images: ['https://placehold.co/600x600.png?text=Dinnerware_1', 'https://placehold.co/600x600.png?text=Dinnerware_2'],
    category: 'Home & Decor',
    brand: 'TableJoy',
    rating: 4.7,
    reviewsCount: 95,
    stock: 50,
    tags: ['kitchen & dining', 'dinnerware', 'home decor', 'ceramics'],
    specifications: { Material: 'Ceramic', Pieces: '16 (4 place settings)', DishwasherSafe: 'Yes', MicrowaveSafe: 'Yes'},
  },
  {
    id: '29',
    name: 'Luxury Egyptian Cotton Bed Sheet Set',
    description: 'Silky soft 800 thread count Egyptian cotton bed sheets.',
    longDescription: 'Experience ultimate comfort with our luxury Egyptian cotton bed sheet set. Made from 100% long-staple Egyptian cotton with an 800 thread count for a silky smooth feel. Set includes flat sheet, fitted sheet, and two pillowcases.',
    price: 7999,
    originalPrice: 9999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'bed sheets',
    images: ['https://placehold.co/600x600.png?text=Sheets_1', 'https://placehold.co/600x600.png?text=Sheets_2'],
    category: 'Home & Decor',
    brand: 'RoyalLinens',
    rating: 4.9,
    reviewsCount: 220,
    stock: 60,
    tags: ['bedding', 'home decor', 'luxury', 'cotton', 'sheets'],
    specifications: { Material: '100% Egyptian Cotton', ThreadCount: '800', SetIncludes: 'Flat sheet, Fitted sheet, 2 Pillowcases', Size: 'Queen/King'},
  },
  {
    id: '54',
    name: 'Velvet Accent Chair',
    description: 'Luxurious velvet accent chair with gold metal legs.',
    longDescription: 'Add a touch of glamour to your living room or bedroom with this chic velvet accent chair. It features soft velvet upholstery, a comfortable cushioned seat, and stylish gold-tone metal legs. Available in multiple rich colors.',
    price: 12990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'velvet chair',
    images: ['https://placehold.co/600x600.png?text=VelvetChair_1', 'https://placehold.co/600x600.png?text=VelvetChair_2'],
    category: 'Home & Decor',
    brand: 'OpulentLiving',
    rating: 4.7,
    reviewsCount: 75,
    stock: 30,
    tags: ['furniture', 'chair', 'accent chair', 'velvet', 'home decor'],
    specifications: { Upholstery: 'Velvet', Frame: 'Wood', Legs: 'Gold-tone Metal', Dimensions: '30" H x 28" W x 29" D'},
  },
  {
    id: '55',
    name: 'Wall Art Canvas Print (Abstract)',
    description: 'Modern abstract canvas print to enhance your wall decor.',
    longDescription: 'This vibrant abstract canvas print adds a contemporary touch to any room. High-quality giclee print on gallery-wrapped canvas, ready to hang. Multiple sizes available.',
    price: 3499,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'abstract art',
    images: ['https://placehold.co/600x600.png?text=AbstractArt_1'],
    category: 'Home & Decor',
    brand: 'ArtScapes',
    rating: 4.6,
    reviewsCount: 110,
    stock: 90,
    tags: ['home decor', 'wall art', 'canvas print', 'abstract art'],
    specifications: { Type: 'Giclee Canvas Print', Style: 'Abstract', Frame: 'Gallery Wrapped', Sizes: 'Various'},
  },
  {
    id: '56',
    name: 'Stainless Steel Cookware Set (10-Piece)',
    description: 'Durable and versatile stainless steel cookware set.',
    longDescription: 'Equip your kitchen with this professional-quality 10-piece stainless steel cookware set. Includes frying pans, saucepans, and a stockpot, all with tri-ply construction for even heating. Oven and dishwasher safe.',
    price: 12990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'cookware set',
    images: ['https://placehold.co/600x600.png?text=Cookware_1', 'https://placehold.co/600x600.png?text=Cookware_2'],
    category: 'Home & Decor',
    brand: 'ChefPro',
    rating: 4.8,
    reviewsCount: 130,
    stock: 40,
    tags: ['kitchen & dining', 'cookware', 'pots and pans', 'stainless steel'],
    specifications: { Material: 'Stainless Steel (Tri-Ply)', Pieces: '10', OvenSafe: 'Up to 500°F', DishwasherSafe: 'Yes'},
  },
  {
    id: '57',
    name: 'Plush Microfiber Bath Towel Set (4-Piece)',
    description: 'Ultra-soft and absorbent microfiber bath towel set.',
    longDescription: 'Wrap yourself in luxury with this plush microfiber bath towel set. Includes four bath towels that are incredibly soft, highly absorbent, and quick-drying. Fade-resistant and durable.',
    price: 1499,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'bath towels',
    images: ['https://placehold.co/600x600.png?text=Towels_1'],
    category: 'Home & Decor',
    brand: 'SoftTouch Linens',
    rating: 4.7,
    reviewsCount: 160,
    stock: 100,
    tags: ['bath', 'towels', 'microfiber', 'bathroom accessories'],
    specifications: { Material: 'Microfiber', SetIncludes: '4 Bath Towels', Size: '30" x 56"', Absorbency: 'High'},
  },
  {
    id: '58',
    name: 'Stackable Storage Bins with Lids (Set of 3)',
    description: 'Versatile stackable storage bins for organizing your home.',
    longDescription: 'Declutter your space with this set of three stackable storage bins. Made from durable clear plastic with secure lids, they are perfect for organizing closets, pantries, or offices. See-through design makes it easy to find items.',
    price: 999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'storage bins',
    images: ['https://placehold.co/600x600.png?text=StorageBins_1'],
    category: 'Home & Decor',
    brand: 'OrganizeIt',
    rating: 4.5,
    reviewsCount: 85,
    stock: 120,
    tags: ['home storage', 'organization', 'bins', 'containers'],
    specifications: { Material: 'Clear Plastic', SetIncludes: '3 Bins with Lids', Stackable: 'Yes', Size: 'Medium'},
  },
  
  // Appliances
  {
    id: '4',
    name: 'Espresso Coffee Machine',
    description: 'Barista-quality espresso at home.',
    longDescription: 'Start your day right with the perfect espresso. This machine features a 15-bar pressure pump, milk frother, and easy-to-use controls. Durable stainless steel construction.',
    price: 16990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'espresso machine',
    images: ['https://placehold.co/600x600.png?text=Espresso_1', 'https://placehold.co/600x600.png?text=Espresso_2'],
    category: 'Appliances',
    brand: 'CafeHome',
    rating: 4.3,
    reviewsCount: 75,
    stock: 60,
    tags: ['coffee maker', 'kitchen', 'appliances', 'home appliances'],
    specifications: { PumpPressure: '15 Bar', Material: 'Stainless Steel', MilkFrother: 'Yes', WaterTank: '1.5L'},
  },
  {
    id: '15',
    name: 'Robot Vacuum Cleaner',
    description: 'Smart robot vacuum with mapping and app control.',
    longDescription: 'Keep your floors clean effortlessly with this smart robot vacuum cleaner. It features intelligent mapping, powerful suction, and can be controlled via a smartphone app or voice commands. Works on hard floors and carpets.',
    price: 22990,
    originalPrice: 27990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'robot vacuum',
    images: ['https://placehold.co/600x600.png?text=VacuumBot_1', 'https://placehold.co/600x600.png?text=VacuumBot_2'],
    category: 'Appliances',
    brand: 'CleanBot',
    rating: 4.5,
    reviewsCount: 115,
    stock: 35,
    tags: ['vacuum cleaner', 'robot vacuum', 'smart home', 'appliances', 'home appliances'],
    specifications: { Navigation: 'LIDAR Mapping', SuctionPower: '2500Pa', AppControl: 'Yes', BatteryLife: '120 minutes'},
  },
  {
    id: '16',
    name: 'Air Fryer XL',
    description: 'Large capacity air fryer for healthy, crispy meals.',
    longDescription: 'Enjoy your favorite fried foods with less oil using the Air Fryer XL. Its large 5.8-quart capacity is perfect for families. Features multiple cooking presets, digital touch screen, and easy-to-clean non-stick basket.',
    price: 7999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'air fryer',
    images: ['https://placehold.co/600x600.png?text=AirFryerXL_1'],
    category: 'Appliances',
    brand: 'KitchenPro',
    rating: 4.7,
    reviewsCount: 180,
    stock: 60,
    tags: ['air fryer', 'kitchen', 'cooking', 'healthy eating', 'appliances', 'home appliances'],
    specifications: { Capacity: '5.8 Quarts', Power: '1700W', Presets: '8 cooking modes', Control: 'Digital Touch Screen'},
  },
  {
    id: '23',
    name: 'Blender Pro',
    description: 'High-speed blender for smoothies and soups.',
    longDescription: 'Create delicious smoothies, soups, and sauces with the Blender Pro. Its powerful motor and stainless steel blades can handle tough ingredients with ease. Features multiple speed settings and a large capacity jar.',
    price: 9990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'kitchen blender',
    images: ['https://placehold.co/600x600.png?text=BlenderPro_1'],
    category: 'Appliances',
    brand: 'BlendMaster',
    rating: 4.4,
    reviewsCount: 110,
    stock: 40,
    tags: ['blender', 'kitchen', 'appliances', 'smoothies', 'home appliances'],
    specifications: { Power: '1200W', JarCapacity: '64 oz', Blades: 'Stainless Steel', Speeds: 'Variable + Pulse'},
  },
  {
    id: '30',
    name: 'High-Efficiency Washing Machine',
    description: 'Front-load washing machine with multiple wash cycles and steam.',
    longDescription: 'Upgrade your laundry routine with this high-efficiency front-load washing machine. It offers a large capacity, various wash cycles including a steam option for sanitization, and quiet operation. Energy Star certified.',
    price: 34990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'washing machine',
    images: ['https://placehold.co/600x600.png?text=WashingMachine_1', 'https://placehold.co/600x600.png?text=WashingMachine_2'],
    category: 'Appliances',
    brand: 'HomeCleanse',
    rating: 4.6,
    reviewsCount: 90,
    stock: 20,
    tags: ['washing machines', 'laundry', 'appliances', 'home appliances', 'energy efficient'],
    specifications: { Type: 'Front-Load', Capacity: '5.0 cu. ft.', Cycles: '12 (including Steam)', EnergyStar: 'Yes'},
  },
  {
    id: '34',
    name: 'Compact Refrigerator (90L)',
    description: 'Space-saving compact refrigerator, ideal for dorms or offices.',
    longDescription: 'This compact refrigerator offers 90 liters of storage space, perfect for small apartments, dorm rooms, or offices. It features an adjustable thermostat, a separate chiller compartment, and a reversible door.',
    price: 9990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'compact fridge',
    images: ['https://placehold.co/600x600.png?text=CompactFridge_1'],
    category: 'Appliances',
    brand: 'CoolZone',
    rating: 4.3,
    reviewsCount: 60,
    stock: 50,
    tags: ['refrigerators', 'compact', 'appliances', 'home appliances', 'dorm'],
    specifications: { Capacity: '90 Liters', Type: 'Compact', ChillerCompartment: 'Yes', ReversibleDoor: 'Yes'},
  },
  {
    id: '59',
    name: 'Smart French Door Refrigerator',
    description: 'Large capacity smart refrigerator with touch screen and ice maker.',
    longDescription: 'This smart French door refrigerator features a 580L capacity, a built-in touch screen for recipes and notes, and an internal ice and water dispenser. Wi-Fi connected for smart home integration.',
    price: 189990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smart fridge',
    images: ['https://placehold.co/600x600.png?text=SmartFridge_1', 'https://placehold.co/600x600.png?text=SmartFridge_2'],
    category: 'Appliances',
    brand: 'FridgeTech',
    rating: 4.8,
    reviewsCount: 120,
    stock: 15,
    tags: ['refrigerators', 'smart home', 'french door', 'kitchen', 'appliances'],
    specifications: { Capacity: '580 Liters', Type: 'French Door', SmartFeatures: 'Touch Screen, Wi-Fi', IceMaker: 'Internal'},
  },
  {
    id: '60',
    name: 'Portable Air Conditioner (1 Ton)',
    description: 'Powerful portable air conditioner for rooms up to 120 sq ft.',
    longDescription: 'Stay cool anywhere with this 1 Ton portable air conditioner. Features include a remote control, programmable timer, and dehumidifier mode. Easy to install and move with caster wheels.',
    price: 28990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'portable ac',
    images: ['https://placehold.co/600x600.png?text=PortableAC_1'],
    category: 'Appliances',
    brand: 'CoolBreeze',
    rating: 4.5,
    reviewsCount: 90,
    stock: 30,
    tags: ['air conditioners', 'portable ac', 'cooling', 'appliances'],
    specifications: { Capacity: '1 Ton', Coverage: 'Up to 120 sq ft', Modes: 'Cool, Fan, Dehumidify', RemoteControl: 'Yes'},
  },
  {
    id: '61',
    name: 'Countertop Microwave Oven (20L)',
    description: 'Compact and efficient countertop microwave oven with presets.',
    longDescription: 'This 20L countertop microwave offers 800W of power and multiple cooking presets for quick and easy meals. Features a sleek stainless steel design and an easy-to-read LED display.',
    price: 5990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'microwave oven',
    images: ['https://placehold.co/600x600.png?text=Microwave_1'],
    category: 'Appliances',
    brand: 'QuickHeat',
    rating: 4.4,
    reviewsCount: 150,
    stock: 60,
    tags: ['microwaves', 'kitchen', 'cooking', 'appliances'],
    specifications: { Capacity: '20 Liters', Power: '800W', Presets: '6 Auto-Cook Menus', Turntable: 'Glass'},
  },
  {
    id: '62',
    name: 'Stainless Steel Dishwasher',
    description: 'Quiet and efficient dishwasher with multiple wash cycles.',
    longDescription: 'This built-in stainless steel dishwasher offers powerful cleaning performance with minimal noise. Features multiple wash cycles, a sanitize option, and adjustable racks to accommodate various dish sizes. Energy Star certified.',
    price: 32990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'kitchen dishwasher',
    images: ['https://placehold.co/600x600.png?text=Dishwasher_1', 'https://placehold.co/600x600.png?text=Dishwasher_2'],
    category: 'Appliances',
    brand: 'SparkleClean',
    rating: 4.6,
    reviewsCount: 70,
    stock: 25,
    tags: ['dishwasher', 'kitchen', 'cleaning', 'appliances', 'energy efficient'],
    specifications: { Type: 'Built-in', Material: 'Stainless Steel', NoiseLevel: '48 dBA', Cycles: '5 (including Sanitize)'},
  },
  {
    id: '63',
    name: 'Wall Mount Kitchen Chimney',
    description: 'Stylish wall mount chimney with powerful suction for a smoke-free kitchen.',
    longDescription: 'Keep your kitchen fresh and odor-free with this sleek wall mount chimney. It features powerful suction, baffle filters for easy cleaning, and energy-efficient LED lights. Modern design to complement your kitchen decor.',
    price: 11990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'kitchen chimney',
    images: ['https://placehold.co/600x600.png?text=Chimney_1'],
    category: 'Appliances',
    brand: 'AeroPure',
    rating: 4.5,
    reviewsCount: 55,
    stock: 35,
    tags: ['chimneys', 'kitchen ventilation', 'cooking', 'appliances'],
    specifications: { Type: 'Wall Mount', Suction: '1200 m³/hr', Filters: 'Baffle Filters', Lights: 'LED'},
  },

  // Grocery
  {
    id: '7',
    name: 'Organic Apples (1kg)',
    description: 'Fresh and juicy organic apples, perfect for snacking.',
    longDescription: 'Enjoy the crisp taste of our certified organic apples. Grown without synthetic pesticides or fertilizers, these apples are a healthy and delicious choice for the whole family. Each pack contains approximately 1kg.',
    price: 249,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'organic apples',
    images: ['https://placehold.co/600x600.png?text=Apples_1'],
    category: 'Grocery',
    brand: 'FarmFresh',
    rating: 4.6,
    reviewsCount: 45,
    stock: 150,
    tags: ['fruits & vegetables', 'grocery', 'fruits', 'organic', 'healthy'],
    specifications: { Weight: '1kg (approx)', Type: 'Organic Gala Apples', Origin: 'Local Farms'},
  },
  {
    id: '8',
    name: 'Whole Wheat Bread Loaf',
    description: 'Nutritious whole wheat bread, freshly baked.',
    longDescription: 'Our whole wheat bread is baked fresh daily using 100% whole grain flour. It\'s a great source of fiber and perfect for sandwiches or toast. No artificial preservatives.',
    price: 65,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'wheat bread',
    images: ['https://placehold.co/600x600.png?text=Bread_1'],
    category: 'Grocery',
    brand: 'BakeryLane',
    rating: 4.4,
    reviewsCount: 30,
    stock: 80,
    tags: ['dairy & bakery', 'grocery', 'bakery', 'bread', 'whole wheat'],
    specifications: { Ingredients: 'Whole wheat flour, water, yeast, salt', Dietary: 'No artificial preservatives'},
  },
  {
    id: '19',
    name: 'Organic Whole Milk (1L)',
    description: 'Fresh, creamy organic whole milk.',
    longDescription: 'Our organic whole milk comes from grass-fed cows and is pasteurized at low temperatures to preserve its natural goodness. Rich in calcium and vitamins, it\'s perfect for drinking, cereal, or cooking. 1 liter carton.',
    price: 75,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'organic milk',
    images: ['https://placehold.co/600x600.png?text=Milk_1'],
    category: 'Grocery',
    brand: 'HappyFarms Dairy',
    rating: 4.7,
    reviewsCount: 88,
    stock: 120,
    tags: ['dairy & bakery', 'grocery', 'dairy', 'milk', 'organic'],
    specifications: { Volume: '1 Liter', Type: 'Organic Whole Milk', FatContent: '3.5%'},
  },
  {
    id: '25',
    name: 'Premium Italian Pasta (500g)',
    description: 'Artisanal Italian pasta made with durum wheat semolina.',
    longDescription: 'Taste the difference with our premium Italian pasta. Made using traditional bronze dies for a rough texture that holds sauces perfectly. Crafted from 100% durum wheat semolina.',
    price: 199,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'italian pasta',
    images: ['https://placehold.co/600x600.png?text=Pasta_1'],
    category: 'Grocery',
    brand: 'Bella Cucina',
    rating: 4.8,
    reviewsCount: 70,
    stock: 200,
    tags: ['staples', 'grocery', 'pasta', 'italian', 'food'],
    specifications: { Weight: '500g', Type: 'Spaghetti', Ingredients: 'Durum wheat semolina, water'},
  },
  {
    id: '31',
    name: 'Gourmet Dark Chocolate Bar (70% Cacao)',
    description: 'Rich and intense dark chocolate bar for connoisseurs.',
    longDescription: 'Indulge in the complex flavors of our gourmet dark chocolate bar. Made with 70% single-origin cacao, it offers notes of fruit and spice with a smooth finish. Perfect for pairing or savoring on its own.',
    price: 350,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'dark chocolate',
    images: ['https://placehold.co/600x600.png?text=Chocolate_1'],
    category: 'Grocery',
    brand: 'ChocoArtisan',
    rating: 4.9,
    reviewsCount: 120,
    stock: 150,
    tags: ['snacks', 'grocery', 'chocolate', 'dark chocolate', 'gourmet', 'sweets'],
    specifications: { CacaoPercentage: '70%', Weight: '100g', Origin: 'Ecuador', Ingredients: 'Cacao beans, cane sugar, cacao butter'},
  },
  {
    id: '64',
    name: 'Fresh Organic Bananas (Bunch)',
    description: 'Naturally ripened organic bananas, rich in potassium.',
    longDescription: 'Our organic bananas are sourced from certified farms and are naturally ripened for optimal flavor and nutrition. A perfect healthy snack or addition to smoothies.',
    price: 80,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'organic bananas',
    images: ['https://placehold.co/600x600.png?text=Bananas_1'],
    category: 'Grocery',
    brand: 'FarmFresh',
    rating: 4.7,
    reviewsCount: 95,
    stock: 180,
    tags: ['fruits & vegetables', 'grocery', 'fruits', 'organic', 'healthy'],
    specifications: { Quantity: 'Bunch (approx 5-7 bananas)', Type: 'Organic Cavendish', Storage: 'Store at room temperature'},
  },
  {
    id: '65',
    name: 'Artisan Sourdough Bread',
    description: 'Crusty artisan sourdough bread with a tangy flavor.',
    longDescription: 'Handcrafted using traditional methods, our artisan sourdough bread has a delightfully chewy crust and a soft, tangy interior. Perfect for sandwiches, toast, or serving with soups.',
    price: 150,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'sourdough bread',
    images: ['https://placehold.co/600x600.png?text=Sourdough_1'],
    category: 'Grocery',
    brand: 'ArtisanBakers',
    rating: 4.9,
    reviewsCount: 110,
    stock: 50,
    tags: ['dairy & bakery', 'grocery', 'bakery', 'bread', 'sourdough'],
    specifications: { Ingredients: 'Flour, water, salt, natural starter', Type: 'Artisan Sourdough Loaf'},
  },
  {
    id: '66',
    name: 'Basmati Rice (5kg Bag)',
    description: 'Premium quality long-grain Basmati rice.',
    longDescription: 'This premium Basmati rice is known for its fragrant aroma and fluffy texture when cooked. Aged to perfection, it\'s ideal for biryanis, pilafs, or as a side dish. 5kg value bag.',
    price: 799,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'basmati rice',
    images: ['https://placehold.co/600x600.png?text=Rice_1'],
    category: 'Grocery',
    brand: 'RoyalHarvest',
    rating: 4.6,
    reviewsCount: 130,
    stock: 90,
    tags: ['staples', 'grocery', 'rice', 'basmati', 'grains'],
    specifications: { Weight: '5kg', Type: 'Long-Grain Basmati', Aging: 'Min. 12 months'},
  },
  {
    id: '67',
    name: 'Kettle Cooked Potato Chips (Sea Salt)',
    description: 'Crunchy kettle-cooked potato chips with a hint of sea salt.',
    longDescription: 'Indulge in these extra crunchy potato chips, kettle-cooked in small batches for superior flavor and texture. Lightly seasoned with natural sea salt. A satisfying snack anytime.',
    price: 45,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'potato chips',
    images: ['https://placehold.co/600x600.png?text=Chips_1'],
    category: 'Grocery',
    brand: 'CrunchTime Snacks',
    rating: 4.5,
    reviewsCount: 105,
    stock: 150,
    tags: ['snacks', 'grocery', 'chips', 'potato chips', 'salty snacks'],
    specifications: { Flavor: 'Sea Salt', Type: 'Kettle Cooked', NetWeight: '150g'},
  },
  {
    id: '68',
    name: 'Cold Pressed Orange Juice (1L)',
    description: '100% pure cold-pressed orange juice, no added sugar.',
    longDescription: 'Enjoy the refreshing taste of pure oranges with our cold-pressed juice. Made from 100% fresh oranges, it retains more vitamins and nutrients. No added sugar, preservatives, or artificial flavors.',
    price: 180,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'orange juice',
    images: ['https://placehold.co/600x600.png?text=OrangeJuice_1'],
    category: 'Grocery',
    brand: 'PureSip',
    rating: 4.8,
    reviewsCount: 90,
    stock: 100,
    tags: ['beverages', 'grocery', 'juice', 'orange juice', 'cold pressed'],
    specifications: { Volume: '1 Liter', Ingredients: '100% Orange Juice', Process: 'Cold Pressed', SugarAdded: 'No'},
  },
  {
    id: '69',
    name: 'Natural Almond Body Wash (500ml)',
    description: 'Gentle and moisturizing natural body wash with almond oil.',
    longDescription: 'Pamper your skin with this natural body wash enriched with sweet almond oil and vitamin E. It cleanses gently while leaving your skin soft, smooth, and hydrated. Paraben and sulfate-free.',
    price: 450,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'body wash',
    images: ['https://placehold.co/600x600.png?text=BodyWash_1'],
    category: 'Grocery',
    brand: 'NaturePure',
    rating: 4.7,
    reviewsCount: 75,
    stock: 80,
    tags: ['personal care', 'grocery', 'body wash', 'natural', 'skincare'],
    specifications: { Scent: 'Almond', Volume: '500ml', KeyIngredients: 'Almond Oil, Vitamin E', FreeFrom: 'Parabens, Sulfates'},
  },
  {
    id: '70',
    name: 'Eco-Friendly Dishwashing Liquid (750ml)',
    description: 'Plant-based dishwashing liquid, tough on grease, gentle on hands.',
    longDescription: 'This eco-friendly dishwashing liquid effectively cuts through grease and grime while being biodegradable and gentle on your skin. Made with plant-derived ingredients and a refreshing citrus scent.',
    price: 220,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'dish soap',
    images: ['https://placehold.co/600x600.png?text=DishSoap_1'],
    category: 'Grocery',
    brand: 'EcoClean Home',
    rating: 4.6,
    reviewsCount: 60,
    stock: 90,
    tags: ['household', 'grocery', 'cleaning', 'dish soap', 'eco-friendly'],
    specifications: { Scent: 'Citrus', Volume: '750ml', Type: 'Plant-based, Biodegradable'},
  },

  // Travel
  {
    id: '17',
    name: 'Weekend Getaway Package: Mountain Retreat',
    description: '2-night stay for two at a scenic mountain lodge.',
    longDescription: 'Escape to the mountains with this relaxing weekend getaway package. Includes a 2-night stay for two people at a charming lodge, daily breakfast, and access to hiking trails. Enjoy breathtaking views and fresh mountain air.',
    price: 14999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'mountain getaway',
    images: ['https://placehold.co/600x600.png?text=Retreat_1', 'https://placehold.co/600x600.png?text=Retreat_2'],
    category: 'Travel',
    brand: 'AdventureEscapes',
    rating: 4.8,
    reviewsCount: 40,
    stock: 10, 
    tags: ['vacation package', 'mountains', 'leisure', 'travel'],
    specifications: { Duration: '2 nights', Includes: 'Accommodation, Breakfast', Location: 'Serene Mountain Valley', Validity: '6 months from purchase'},
  },
  {
    id: '18',
    name: 'City Tour: Historical Landmarks',
    description: 'Guided walking tour of the city\'s most famous historical sites.',
    longDescription: 'Discover the rich history of the city with our expert-guided walking tour. Visit iconic landmarks, learn fascinating stories, and immerse yourself in the local culture. Tour lasts approximately 3 hours.',
    price: 1500, 
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'city tour',
    images: ['https://placehold.co/600x600.png?text=CityTour_1'],
    category: 'Travel',
    brand: 'UrbanExplorers',
    rating: 4.6,
    reviewsCount: 75,
    stock: 50, 
    tags: ['city tour', 'tourism', 'historical', 'guided tour', 'travel'],
    specifications: { Type: 'Walking Tour', Duration: '3 hours', GroupSize: 'Max 15 people', Language: 'English'},
  },
  {
    id: '24',
    name: 'Beach Holiday Package: Tropical Paradise',
    description: '5-night all-inclusive stay at a luxury beach resort.',
    longDescription: 'Indulge in a tropical getaway with this 5-night all-inclusive package. Stay at a stunning beach resort, enjoy gourmet meals, beverages, and various water sports activities. Perfect for a romantic escape or family vacation.',
    price: 59990,
    originalPrice: 74990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'beach holiday',
    images: ['https://placehold.co/600x600.png?text=BeachHoliday_1', 'https://placehold.co/600x600.png?text=BeachHoliday_2', 'https://placehold.co/600x600.png?text=BeachHoliday_3'],
    category: 'Travel',
    brand: 'SunSeeker Vacations',
    rating: 4.9,
    reviewsCount: 65,
    stock: 5,
    tags: ['vacation package', 'beach', 'all-inclusive', 'luxury', 'travel'],
    specifications: { Duration: '5 nights', Includes: 'All meals, drinks, activities', Location: 'Tropical Island Resort', Accommodation: 'Ocean View Suite'},
  },
  {
    id: '35',
    name: 'Adventure Backpack (50L)',
    description: 'Durable and versatile backpack for hiking and travel.',
    longDescription: 'Embark on your next adventure with this 50L backpack. Made from water-resistant nylon, it features multiple compartments, adjustable straps, a comfortable padded back panel, and an integrated rain cover. Perfect for multi-day hikes or backpacking trips.',
    price: 3499,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'hiking backpack',
    images: ['https://placehold.co/600x600.png?text=Backpack_1', 'https://placehold.co/600x600.png?text=Backpack_2'],
    category: 'Travel', 
    brand: 'TrailBlazer Gear',
    rating: 4.6,
    reviewsCount: 140,
    stock: 90,
    tags: ['backpacks', 'hiking', 'outdoors', 'gear', 'travel'],
    specifications: { Capacity: '50 Liters', Material: 'Water-resistant Nylon', RainCover: 'Integrated', Compartments: 'Multiple'},
  },
  {
    id: '71',
    name: 'Lightweight Carry-On Spinner Luggage',
    description: 'Durable and lightweight carry-on suitcase with spinner wheels.',
    longDescription: 'Travel light and smart with this carry-on spinner luggage. Constructed from durable polycarbonate, it meets most airline size restrictions and features smooth spinner wheels for easy maneuverability. Includes TSA lock.',
    price: 3499,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'carryon luggage',
    images: ['https://placehold.co/600x600.png?text=CarryOn_1', 'https://placehold.co/600x600.png?text=CarryOn_2'],
    category: 'Travel',
    brand: 'AeroLite',
    rating: 4.7,
    reviewsCount: 180,
    stock: 100,
    tags: ['luggage', 'carry-on', 'suitcase', 'travel gear'],
    specifications: { Material: 'Polycarbonate', Size: '20 inch (Carry-on)', Wheels: '4 Spinner Wheels', Lock: 'TSA-Approved'},
  },
  {
    id: '72',
    name: 'Travel Neck Pillow (Memory Foam)',
    description: 'Ergonomic memory foam neck pillow for comfortable travel.',
    longDescription: 'Ensure a comfortable journey with this ergonomic memory foam neck pillow. It provides excellent support for your neck and head, helping to prevent stiffness during long flights or car rides. Includes a washable cover.',
    price: 899,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'neck pillow',
    images: ['https://placehold.co/600x600.png?text=NeckPillow_1'],
    category: 'Travel',
    brand: 'ComfyJourney',
    rating: 4.8,
    reviewsCount: 250,
    stock: 150,
    tags: ['travel accessories', 'neck pillow', 'comfort', 'memory foam'],
    specifications: { Material: 'Memory Foam, Velvet Cover', Shape: 'U-Shaped', WashableCover: 'Yes'},
  },
  {
    id: '73',
    name: 'Universal Travel Adapter',
    description: 'All-in-one universal travel adapter for worldwide use.',
    longDescription: 'Stay powered up wherever you go with this universal travel adapter. Compatible with outlets in over 150 countries, it features multiple USB ports for charging several devices simultaneously. Compact and safe design.',
    price: 999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'travel adapter',
    images: ['https://placehold.co/600x600.png?text=Adapter_1'],
    category: 'Travel',
    brand: 'PowerLink Global',
    rating: 4.6,
    reviewsCount: 190,
    stock: 120,
    tags: ['travel electronics', 'travel adapter', 'charger', 'gadgets'],
    specifications: { Compatibility: 'US/EU/UK/AU Plugs', USBPorts: '4 (3 USB-A, 1 USB-C)', SafetyFeatures: 'Surge Protection, Overload Fuse'},
  },
  // Sports & Outdoors
  {
    id: '6',
    name: 'Yoga Mat Premium',
    description: 'Eco-friendly, non-slip yoga mat for all practices.',
    longDescription: 'Enhance your yoga practice with this premium, eco-friendly mat. Made from natural tree rubber, it offers excellent grip and cushioning. Lightweight and easy to carry.',
    price: 2499,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'yoga mat',
    images: ['https://placehold.co/600x600.png?text=YogaMat_1'],
    category: 'Sports & Outdoors',
    brand: 'ZenFlow',
    rating: 4.9,
    reviewsCount: 300,
    stock: 120,
    tags: ['yoga', 'fitness', 'sports'],
    specifications: { Material: 'Natural Tree Rubber', Thickness: '5mm', Dimensions: '72" x 24"', EcoFriendly: 'Yes'},
  },
  {
    id: '74',
    name: 'Professional Badminton Racket Set',
    description: 'Lightweight carbon fiber badminton racket set with shuttlecocks.',
    longDescription: 'Elevate your game with this professional badminton racket set. Includes two lightweight carbon fiber rackets for quick swings and powerful shots, plus a tube of durable shuttlecocks. Comes with a convenient carrying bag.',
    price: 2999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'badminton racket',
    images: ['https://placehold.co/600x600.png?text=BadmintonSet_1', 'https://placehold.co/600x600.png?text=BadmintonSet_2'],
    category: 'Sports & Outdoors',
    brand: 'ProSmash',
    rating: 4.7,
    reviewsCount: 150,
    stock: 80,
    tags: ['badminton', 'racket sports', 'sports equipment', 'outdoor games'],
    specifications: { Material: 'Carbon Fiber', SetIncludes: '2 Rackets, 6 Shuttlecocks, Bag', Weight: '85g (per racket)'},
  },
  {
    id: '75',
    name: 'Cricket Bat (Kashmir Willow)',
    description: 'Full-size Kashmir willow cricket bat for club players.',
    longDescription: 'This full-size cricket bat is crafted from premium Kashmir willow, offering excellent balance and power for club-level players. Features a comfortable grip and traditional shaping for classic stroke play.',
    price: 1899,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'cricket bat',
    images: ['https://placehold.co/600x600.png?text=CricketBat_1'],
    category: 'Sports & Outdoors',
    brand: 'SixerStallion',
    rating: 4.5,
    reviewsCount: 110,
    stock: 90,
    tags: ['cricket', 'sports equipment', 'bat', 'team sports'],
    specifications: { Material: 'Kashmir Willow', Size: 'Full Size (SH)', Handle: 'Short Handle, Cane'},
  },
  {
    id: '76',
    name: 'Adjustable Dumbbell Set (24kg Pair)',
    description: 'Space-saving adjustable dumbbell set, from 2.5kg to 24kg each.',
    longDescription: 'Maximize your home workouts with this adjustable dumbbell set. Easily switch weights from 2.5kg to 24kg on each dumbbell with a simple dial system. Replaces multiple sets of traditional dumbbells.',
    price: 14990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'adjustable dumbbells',
    images: ['https://placehold.co/600x600.png?text=Dumbbells_1', 'https://placehold.co/600x600.png?text=Dumbbells_2'],
    category: 'Sports & Outdoors',
    brand: 'FitFlex',
    rating: 4.8,
    reviewsCount: 200,
    stock: 50,
    tags: ['fitness', 'home gym', 'dumbbells', 'strength training', 'workout'],
    specifications: { WeightRange: '2.5kg - 24kg (per dumbbell)', Adjustments: '15 settings', Includes: '2 Dumbbells, 2 Trays'},
  },
  {
    id: '77',
    name: 'Professional Football (Size 5)',
    description: 'Durable, all-weather professional football for matches and training.',
    longDescription: 'This Size 5 professional football is designed for optimal performance in all weather conditions. Features a thermally bonded seamless surface for predictable trajectory and better touch. FIFA Quality Pro certified.',
    price: 1299,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'football ball',
    images: ['https://placehold.co/600x600.png?text=Football_1'],
    category: 'Sports & Outdoors',
    brand: 'GoalMaster',
    rating: 4.6,
    reviewsCount: 180,
    stock: 100,
    tags: ['football', 'soccer', 'sports equipment', 'team sports', 'ball'],
    specifications: { Size: '5', Material: 'Polyurethane', Construction: 'Thermally Bonded', Certification: 'FIFA Quality Pro'},
  },
  {
    id: '78',
    name: 'Resistance Bands Set (5 Levels)',
    description: 'Versatile set of 5 resistance bands for full-body workouts.',
    longDescription: 'This set of 5 loop resistance bands offers varying levels of resistance (X-Light to X-Heavy) for a wide range of exercises. Perfect for strength training, yoga, Pilates, and rehabilitation. Made from durable natural latex.',
    price: 799,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'resistance bands',
    images: ['https://placehold.co/600x600.png?text=ResBands_1'],
    category: 'Sports & Outdoors',
    brand: 'CoreStrength',
    rating: 4.7,
    reviewsCount: 250,
    stock: 150,
    tags: ['fitness', 'resistance bands', 'workout', 'home gym', 'exercise'],
    specifications: { Levels: '5 (X-Light, Light, Medium, Heavy, X-Heavy)', Material: 'Natural Latex', Includes: '5 Bands, Carry Bag'},
  },
  {
    id: '79',
    name: 'Camping Tent (4-Person)',
    description: 'Spacious and waterproof 4-person dome tent for camping.',
    longDescription: 'Enjoy the great outdoors with this easy-to-setup 4-person dome tent. Features waterproof fabric, good ventilation, and a durable frame. Includes a carry bag for convenient transport and storage.',
    price: 4990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'camping tent',
    images: ['https://placehold.co/600x600.png?text=Tent_1', 'https://placehold.co/600x600.png?text=Tent_2'],
    category: 'Sports & Outdoors',
    brand: 'OutdoorSpirit',
    rating: 4.5,
    reviewsCount: 90,
    stock: 60,
    tags: ['camping', 'outdoors', 'hiking', 'tent', 'gear'],
    specifications: { Capacity: '4 Person', Type: 'Dome Tent', WaterproofRating: '2000mm', PackedWeight: '4.5kg'},
  },
  {
    id: '80',
    name: 'Basketball Hoop and Stand (Portable)',
    description: 'Adjustable height portable basketball hoop system for all ages.',
    longDescription: 'Practice your shots anywhere with this portable basketball hoop. The height can be adjusted from 6.6 ft to 10 ft, making it suitable for kids and adults. Features a durable backboard and a base that can be filled with water or sand for stability.',
    price: 9990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'basketball hoop',
    images: ['https://placehold.co/600x600.png?text=Hoop_1'],
    category: 'Sports & Outdoors',
    brand: 'SlamDunk Pro',
    rating: 4.4,
    reviewsCount: 75,
    stock: 40,
    tags: ['basketball', 'sports equipment', 'outdoor games', 'hoop'],
    specifications: { HeightAdjustment: '6.6 ft - 10 ft', BackboardMaterial: 'Polycarbonate', BaseCapacity: '100 Liters'},
  },
  {
    id: '81',
    name: 'Cycling Helmet (Adult)',
    description: 'Lightweight and ventilated cycling helmet with adjustable fit.',
    longDescription: 'Stay safe on your rides with this adult cycling helmet. It features a lightweight in-mold construction, excellent ventilation to keep you cool, and an adjustable dial fit system for a secure and comfortable fit. Meets safety standards.',
    price: 1999,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'cycling helmet',
    images: ['https://placehold.co/600x600.png?text=Helmet_1', 'https://placehold.co/600x600.png?text=Helmet_2'],
    category: 'Sports & Outdoors',
    brand: 'RideSafe',
    rating: 4.7,
    reviewsCount: 130,
    stock: 110,
    tags: ['cycling', 'safety gear', 'helmet', 'bike accessories', 'sports'],
    specifications: { Size: 'Adult Universal (Adjustable)', Construction: 'In-mold Polycarbonate Shell', Ventilation: '22 Vents', SafetyCert: 'CPSC Certified'},
  },
  {
    id: '82',
    name: 'Professional Tennis Racket',
    description: 'Graphite tennis racket for advanced players, offering power and control.',
    longDescription: 'Unleash your potential on the court with this professional-grade tennis racket. Made from high-modulus graphite for a perfect blend of power and control. Suitable for advanced players seeking precision and spin.',
    price: 7990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'tennis racket',
    images: ['https://placehold.co/600x600.png?text=TennisRacket_1'],
    category: 'Sports & Outdoors',
    brand: 'AceCourt',
    rating: 4.8,
    reviewsCount: 85,
    stock: 70,
    tags: ['tennis', 'racket sports', 'sports equipment', 'professional'],
    specifications: { Material: 'Graphite', HeadSize: '100 sq. in.', StringPattern: '16x19', UnstrungWeight: '300g'},
  },
  {
    id: '83',
    name: 'Hiking Boots (Waterproof)',
    description: 'Durable waterproof hiking boots for challenging trails.',
    longDescription: 'Conquer any trail with these rugged waterproof hiking boots. Featuring a breathable membrane, Vibram outsole for superior grip, and ankle support for stability. Designed for comfort and durability on long treks.',
    price: 6990,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'hiking boots',
    images: ['https://placehold.co/600x600.png?text=HikingBoots_1', 'https://placehold.co/600x600.png?text=HikingBoots_2'],
    category: 'Sports & Outdoors',
    brand: 'PeakTrekker',
    rating: 4.6,
    reviewsCount: 160,
    stock: 95,
    tags: ['hiking', 'footwear', 'boots', 'outdoors', 'waterproof', 'gear'],
    specifications: { Waterproofing: 'Gore-Tex Membrane', Outsole: 'Vibram Megagrip', UpperMaterial: 'Leather and Synthetic Mesh'},
  },
];

export const mockReviews: Review[] = [
  { id: 'r1', productId: '1', author: 'Arjun K.', rating: 5, comment: 'Amazing phone, super fast and great camera!', date: '2023-10-01' },
  { id: 'r2', productId: '1', author: 'Priya S.', rating: 4, comment: 'Good phone, battery could be slightly better.', date: '2023-10-05' },
  { id: 'r3', productId: '2', author: 'Mike B.', rating: 5, comment: 'Best headphones I have ever owned. Noise cancellation is superb.', date: '2023-09-15' },
  { id: 'r4', productId: '2', author: 'Lisa K.', rating: 4, comment: 'Very comfortable and great sound, a bit pricey though.', date: '2023-09-20' },
  { id: 'r5', productId: '7', author: 'Sarah P.', rating: 5, comment: 'These apples are delicious and so fresh!', date: '2023-11-01' },
  { id: 'r6', productId: '8', author: 'Tom W.', rating: 4, comment: 'Good solid bread, makes great toast.', date: '2023-11-02' },
  { id: 'r7', productId: '9', author: 'Deepa M.', rating: 4, comment: 'Great value for the price, does everything I need.', date: '2023-10-20' },
  { id: 'r8', productId: '10', author: 'Anjali V.', rating: 5, comment: 'Love this dress! Perfect for summer.', date: '2023-07-10' },
  { id: 'r9', productId: '12', author: 'Rohan G.', rating: 5, comment: 'Absolute beast of a laptop. Runs everything smoothly.', date: '2023-10-25' },
  { id: 'r10', productId: '15', author: 'Maria C.', rating: 4, comment: 'Robot vacuum is a lifesaver. Cleans pretty well.', date: '2023-09-30' },
  { id: 'r11', productId: '17', author: 'David K.', rating: 5, comment: 'The mountain retreat was fantastic. So peaceful.', date: '2023-08-15' },
  { id: 'r12', productId: '19', author: 'Laura B.', rating: 5, comment: 'Creamy and delicious milk, my kids love it!', date: '2023-11-05' },
  { id: 'r13', productId: '20', author: 'Chris P.', rating: 4, comment: 'Great sound for its size. Battery life is decent.', date: '2023-10-15' },
  { id: 'r14', productId: '26', author: 'Sam K.', rating: 5, comment: 'This phone is incredible! The camera is out of this world.', date: '2023-11-10'},
  { id: 'r15', productId: '28', author: 'Olivia M.', rating: 4, comment: 'Love my new smartwatch, tracks everything accurately.', date: '2023-11-08'},
  { id: 'r16', productId: '32', author: 'Robert H.', rating: 5, comment: 'Amazing camera quality, the lens is superb.', date: '2023-10-30'},
  { id: 'r17', productId: '36', author: 'Alice W.', rating: 5, comment: 'The new iFruit Phone is a game changer! So smooth.', date: '2023-11-12' },
  { id: 'r18', productId: '37', author: 'Bob C.', rating: 4, comment: 'Pixel Perfect 9 camera is truly smart. Great photos.', date: '2023-11-11' },
  { id: 'r19', productId: '42', author: 'Charlie E.', rating: 5, comment: 'UltraBook Slim Pro is perfect for my work travels.', date: '2023-11-09' },
  { id: 'r20', productId: '46', author: 'Diana F.', rating: 5, comment: 'NextGen Gaming Console X is mind-blowing! The graphics are insane.', date: '2023-11-14' },
  { id: 'r21', productId: '54', author: 'Ethan G.', rating: 4, comment: 'Velvet accent chair looks stunning in my living room.', date: '2023-11-07' },
  { id: 'r22', productId: '59', author: 'Fiona H.', rating: 5, comment: 'This smart fridge is amazing! Love the touch screen.', date: '2023-11-13' },
  { id: 'r23', productId: '64', author: 'George I.', rating: 5, comment: 'Best organic bananas I\'ve had. So sweet!', date: '2023-11-06' },
  { id: 'r24', productId: '71', author: 'Hannah J.', rating: 4, comment: 'Lightweight carry-on, perfect for short trips.', date: '2023-11-05' },
  { id: 'r25', productId: '6', author: 'Zoya A.', rating: 5, comment: 'This yoga mat has excellent grip. Love the color too!', date: '2023-11-15'},
  { id: 'r26', productId: '74', author: 'Raj V.', rating: 4, comment: 'Good quality badminton set for the price.', date: '2023-11-16'},
  { id: 'r27', productId: '75', author: 'Amit S.', rating: 5, comment: 'Nice bat, good pickup and power.', date: '2023-11-17'},
  { id: 'r28', productId: '76', author: 'Priya K.', rating: 5, comment: 'Adjustable dumbbells are so convenient for home workouts!', date: '2023-11-18'},
  { id: 'r29', productId: '77', author: 'Kevin D.', rating: 4, comment: 'The football feels great and flies true.', date: '2023-11-19'},
];

export function getAllProducts(): Product[] {
  return mockProducts;
}

export function getProductById(id: string): Product | undefined {
  return mockProducts.find(product => product.id === id);
}

export function getReviewsByProductId(productId: string): Review[] {
  return mockReviews.filter(review => review.productId === productId);
}

