
import type { Product, Review } from '@/types';

export const mockProducts: Product[] = [
  // Existing Mobiles
  {
    id: '1',
    name: 'Smartphone Pro X (TechCorp)',
    description: 'Latest model with AI camera and long battery life.',
    longDescription: 'Experience the future with Smartphone Pro X. Featuring a stunning 6.7-inch OLED display, the new A17 Bionic chip, and an advanced triple-camera system with LiDAR. Enjoy all-day battery life and 5G connectivity. Perfect for professionals and tech enthusiasts.',
    price: 799.99,
    originalPrice: 899.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smartphone tech',
    images: [
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
      'https://placehold.co/600x600.png',
    ],
    category: 'Mobiles',
    brand: 'TechCorp', // Generic brand
    rating: 4.5,
    reviewsCount: 120,
    stock: 50,
    tags: ['smartphone', 'mobile', 'tech', 'electronics'],
    specifications: { Screen: '6.7" OLED', Processor: 'A17 Bionic', RAM: '8GB', Storage: '256GB', Camera: '48MP Triple-Lens'},
  },
  {
    id: '9',
    name: 'Smartphone Lite Y (BudgetMobile)',
    description: 'Affordable smartphone with essential features.',
    longDescription: 'The Smartphone Lite Y offers a great balance of performance and affordability. It features a 6.2-inch HD+ display, a reliable octa-core processor, and a dual-camera setup. Ideal for everyday use and staying connected.',
    price: 199.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smartphone budget mobile',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Mobiles',
    brand: 'BudgetMobile', // Generic brand
    rating: 4.2,
    reviewsCount: 85,
    stock: 70,
    tags: ['smartphone', 'mobile', 'budget', 'electronics'],
    specifications: { Screen: '6.2" HD+ LCD', Processor: 'Octa-core', RAM: '4GB', Storage: '64GB', Camera: '13MP Dual-Lens'},
  },
  {
    id: '26',
    name: 'GalaxyPrime Ultra 24', // Samsung-like
    description: 'Top-tier smartphone with cutting-edge technology and features.',
    longDescription: 'The GalaxyPrime Ultra 24 pushes the boundaries of mobile technology. With its dynamic AMOLED 3X display, revolutionary 200MP camera system, and the fastest processor yet, it offers an unparalleled experience. Includes S-Pen support.',
    price: 1199.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smartphone flagship premium',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Mobiles',
    brand: 'Samsung',
    rating: 4.9,
    reviewsCount: 350,
    stock: 40,
    tags: ['smartphone', 'mobile', 'flagship', 'premium', 'tech', 'samsung'],
    specifications: { Screen: '6.8" Dynamic AMOLED 3X', Processor: 'Snapdragon Gen 4', RAM: '12GB', Storage: '512GB', Camera: '200MP Quad-Camera', Battery: '5000mAh'},
  },
  // New Mobiles
  {
    id: '36',
    name: 'iFruit Phone 16 Pro', // Apple-like
    description: 'The ultimate iFruit experience with ProMotion display and cinematic mode.',
    longDescription: 'Discover the iFruit Phone 16 Pro, featuring a super-responsive ProMotion display, A18 Pro chip for breakthrough performance, and an advanced camera system for incredible photos and videos in any light. Cinematic mode now in 4K HDR.',
    price: 1099.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'apple iphone smartphone',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Mobiles',
    brand: 'Apple',
    rating: 4.8,
    reviewsCount: 450,
    stock: 30,
    tags: ['apple', 'ifruit', 'smartphone', 'premium', 'ios'],
    specifications: { Display: '6.1" Super Retina XDR', Chip: 'A18 Pro', Camera: '48MP Main, ProRAW', Storage: '256GB', OS: 'iFruitOS 18'},
  },
  {
    id: '37',
    name: 'Pixel Perfect 9', // Google-like
    description: 'The smarts of Googel in a powerful, helpful phone.',
    longDescription: 'Pixel Perfect 9 delivers an amazing camera experience powered by Googel AI, the Tensor G4 chip for speed and security, and features that adapt to you. Enjoy all-day battery and exclusive Pixel features.',
    price: 899.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'google pixel smartphone',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Mobiles',
    brand: 'Google',
    rating: 4.7,
    reviewsCount: 320,
    stock: 45,
    tags: ['google', 'pixel', 'smartphone', 'android', 'ai camera'],
    specifications: { Display: '6.3" OLED, 120Hz', Chip: 'Tensor G4', Camera: '50MP Advanced AI', Storage: '128GB', OS: 'Android 15'},
  },
  {
    id: '38',
    name: 'OnePlus Ace 12', // OnePlus-like
    description: 'Flagship performance with incredibly fast charging.',
    longDescription: 'The OnePlus Ace 12 combines speed and power with a sleek design. Featuring a 120Hz Fluid AMOLED display, the latest Snapdragon processor, and 150W SUPERVOOC charging. Hasselblad camera for stunning photos.',
    price: 749.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'oneplus smartphone fast',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Mobiles',
    brand: 'OnePlus',
    rating: 4.6,
    reviewsCount: 280,
    stock: 50,
    tags: ['oneplus', 'smartphone', 'fast charging', 'android'],
    specifications: { Display: '6.7" Fluid AMOLED, 120Hz', Processor: 'Snapdragon 8 Gen 3', Camera: '50MP Hasselblad', Charging: '150W SUPERVOOC', RAM: '12GB'},
  },
  {
    id: '39',
    name: 'XiaoMi HyperPhone 14', // Xiaomi-like
    description: 'Cutting-edge features at an unbeatable price point.',
    longDescription: 'XiaoMi HyperPhone 14 offers a premium experience without the premium price. Boasting a vibrant AMOLED display, a versatile 108MP camera system, and powerful performance for gaming and multitasking. Long-lasting battery with fast charging.',
    price: 499.00,
    originalPrice: 549.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'xiaomi smartphone value',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Mobiles',
    brand: 'Xiaomi',
    rating: 4.5,
    reviewsCount: 550,
    stock: 60,
    tags: ['xiaomi', 'smartphone', 'value', 'android', 'miui'],
    specifications: { Display: '6.67" AMOLED, 120Hz', Camera: '108MP Triple', Processor: 'Snapdragon 7+ Gen 2', Battery: '5000mAh, 67W Turbo Charging', RAM: '8GB'},
  },
  {
    id: '40',
    name: 'RealChampion GT Neo 7', // Realme-like
    description: 'Performance-driven smartphone for gaming enthusiasts.',
    longDescription: 'The RealChampion GT Neo 7 is built for speed. With its powerful Dimensity processor, dedicated gaming mode, and ultra-smooth display, it offers an immersive gaming experience. Stylish design with vapor chamber cooling.',
    price: 399.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'realme smartphone gaming',
    images: ['https://placehold.co/600x600.png'],
    category: 'Mobiles',
    brand: 'Realme',
    rating: 4.4,
    reviewsCount: 210,
    stock: 55,
    tags: ['realme', 'smartphone', 'gaming', 'performance', 'android'],
    specifications: { Display: '6.74" AMOLED, 144Hz', Processor: 'Dimensity 9000+', RAM: '12GB', Storage: '256GB', Cooling: 'Vapor Chamber'},
  },
  {
    id: '41',
    name: 'OPPO Find X8 Pro', // OPPO-like
    description: 'Masterpiece of design and camera innovation.',
    longDescription: 'The OPPO Find X8 Pro is a testament to aesthetic design and photographic excellence. Featuring a unique ceramic body, Hasselblad camera co-engineered system, and a stunning LTPO AMOLED display. Experience pro-level photography.',
    price: 999.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'oppo smartphone camera',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Mobiles',
    brand: 'OPPO',
    rating: 4.7,
    reviewsCount: 190,
    stock: 35,
    tags: ['oppo', 'smartphone', 'camera', 'design', 'premium'],
    specifications: { Display: '6.8" LTPO AMOLED, 120Hz', Camera: 'Dual 50MP Hasselblad', Material: 'Ceramic', Processor: 'Snapdragon 8 Gen 3', OS: 'ColorOS'},
  },

  // Existing Electronics
  {
    id: '2',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immersive sound quality with active noise cancellation.',
    longDescription: 'Dive into pure sound with these premium wireless headphones. Featuring industry-leading noise cancellation, crystal-clear audio, and up to 30 hours of battery life. Comfortable over-ear design for extended listening sessions.',
    price: 249.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'headphones audio',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'AudioPhonic',
    rating: 4.8,
    reviewsCount: 250,
    stock: 100,
    tags: ['audio', 'headphones', 'music', 'electronics'],
    specifications: { Type: 'Over-ear', Connectivity: 'Bluetooth 5.2', BatteryLife: '30 hours', NoiseCancellation: 'Active'},
  },
  {
    id: '3',
    name: 'Ultra HD Smart TV 55"',
    description: 'Stunning 4K resolution with smart features.',
    longDescription: 'Transform your viewing experience with this 55-inch 4K Ultra HD Smart TV. Enjoy vibrant colors, sharp details, and access to all your favorite streaming apps. Slim design that complements any living space.',
    price: 499.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smart tv entertainment',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'VisionMax',
    rating: 4.6,
    reviewsCount: 95,
    stock: 30,
    tags: ['tv', 'home entertainment', 'smart tv', 'electronics'],
    specifications: { ScreenSize: '55 inch', Resolution: '4K Ultra HD', SmartFeatures: 'Yes, WebOS', HDR: 'HDR10, Dolby Vision'},
  },
  {
    id: '12',
    name: 'Gaming Laptop Predator Z',
    description: 'High-performance gaming laptop with RTX graphics.',
    longDescription: 'Dominate the game with the Predator Z gaming laptop. Equipped with the latest Intel Core i7 processor, NVIDIA GeForce RTX graphics, a 144Hz display, and advanced cooling system. Ready for AAA titles and intensive multitasking.',
    price: 1499.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'laptop gaming tech',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'CyberPower',
    rating: 4.7,
    reviewsCount: 70,
    stock: 25,
    tags: ['laptops', 'gaming', 'pc', 'electronics'],
    specifications: { Processor: 'Intel Core i7 (12th Gen)', Graphics: 'NVIDIA GeForce RTX 3070', Display: '15.6" FHD 144Hz', RAM: '16GB DDR5', Storage: '1TB NVMe SSD'},
  },
  {
    id: '20',
    name: 'Bluetooth Speaker Portable',
    description: 'Compact and powerful portable Bluetooth speaker.',
    longDescription: 'Take your music anywhere with this portable Bluetooth speaker. It offers rich sound, deep bass, and a rugged waterproof design. Up to 12 hours of playtime on a single charge.',
    price: 59.99,
    originalPrice: 79.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'speaker bluetooth portable',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'SoundGo',
    rating: 4.5,
    reviewsCount: 150,
    stock: 80,
    tags: ['audio', 'speaker', 'bluetooth', 'portable', 'electronics'],
    specifications: { Connectivity: 'Bluetooth 5.0', Playtime: '12 hours', Waterproof: 'IPX7', Power: '10W'},
  },
  {
    id: '28',
    name: 'Smartwatch Series 8',
    description: 'Advanced smartwatch with health tracking and GPS.',
    longDescription: 'Stay connected and track your health with the Smartwatch Series 8. Features a bright always-on display, ECG, blood oxygen monitoring, GPS, and cellular connectivity options. Water-resistant and customizable.',
    price: 399.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'smartwatch tech wearable',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'ConnectWear',
    rating: 4.7,
    reviewsCount: 180,
    stock: 70,
    tags: ['smartwatch', 'wearable', 'health', 'fitness', 'electronics'],
    specifications: { Display: 'Always-On Retina', HealthSensors: 'ECG, SpO2, Heart Rate', GPS: 'Built-in', WaterResistance: '50 meters'},
  },
  {
    id: '32',
    name: 'Professional DSLR Camera Kit',
    description: 'Full-frame DSLR camera with 24-70mm lens kit.',
    longDescription: 'Capture stunning professional-quality images and videos with this full-frame DSLR camera. The kit includes a versatile 24-70mm f/2.8 lens, offering exceptional sharpness and low-light performance. Ideal for enthusiasts and professionals.',
    price: 2499.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'camera dslr professional',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'PhotoPro',
    rating: 4.8,
    reviewsCount: 110,
    stock: 15,
    tags: ['cameras', 'dslr', 'photography', 'electronics', 'professional'],
    specifications: { Sensor: 'Full-Frame CMOS', Megapixels: '30.4 MP', LensIncluded: '24-70mm f/2.8', Video: '4K UHD', ISO: '100-32000 (expandable)'},
  },
  // New Electronics
  {
    id: '42',
    name: 'UltraBook Slim Pro',
    description: 'Lightweight and powerful ultrabook for productivity on the go.',
    longDescription: 'The UltraBook Slim Pro is designed for professionals who need portability and performance. It features a stunning QHD display, long battery life, and a sleek aluminum chassis. Weighs just 2.5 lbs.',
    price: 1299.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'laptop ultrabook business',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'LapTech',
    rating: 4.7,
    reviewsCount: 90,
    stock: 40,
    tags: ['laptops', 'ultrabook', 'business', 'portable', 'electronics'],
    specifications: { Display: '14" QHD IPS', Processor: 'Intel Core i7 (13th Gen)', RAM: '16GB LPDDR5', Storage: '1TB PCIe SSD', Weight: '2.5 lbs'},
  },
  {
    id: '43',
    name: 'OLED Smart TV 65" Cinema Edition',
    description: 'Immersive 65-inch OLED TV with cinematic sound and picture.',
    longDescription: 'Experience movies like never before with the 65" OLED Smart TV Cinema Edition. Perfect blacks, infinite contrast, and vibrant colors combined with Dolby Atmos sound create a true cinematic experience in your home.',
    price: 1899.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'oled tv smart',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'CineView',
    rating: 4.9,
    reviewsCount: 150,
    stock: 20,
    tags: ['tvs', 'oled', 'smart tv', 'home theater', 'electronics'],
    specifications: { ScreenSize: '65 inch', PanelType: 'OLED', Resolution: '4K Ultra HD', Sound: 'Dolby Atmos', SmartPlatform: 'Android TV'},
  },
  {
    id: '44',
    name: 'True Wireless Earbuds Elite',
    description: 'Premium true wireless earbuds with adaptive noise cancellation.',
    longDescription: 'The True Wireless Earbuds Elite offer superior sound quality, adaptive noise cancellation that adjusts to your surroundings, and a comfortable, secure fit. Long battery life with wireless charging case.',
    price: 179.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'earbuds wireless audio',
    images: ['https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'AudioPhonic',
    rating: 4.6,
    reviewsCount: 220,
    stock: 120,
    tags: ['audio', 'earbuds', 'true wireless', 'noise cancelling', 'electronics'],
    specifications: { Connectivity: 'Bluetooth 5.3', ANC: 'Adaptive', Battery: '8 hrs (earbuds), 32 hrs (total)', WirelessCharging: 'Yes'},
  },
  {
    id: '45',
    name: 'Mirrorless Camera Alpha One',
    description: 'Professional-grade mirrorless camera with advanced autofocus.',
    longDescription: 'The Alpha One mirrorless camera delivers breathtaking image quality and unmatched autofocus performance. Featuring a high-resolution full-frame sensor, 8K video recording, and robust build quality. Ideal for professionals.',
    price: 3499.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'camera mirrorless professional',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'SonyAlpha', // Sony-like
    rating: 4.9,
    reviewsCount: 95,
    stock: 10,
    tags: ['cameras', 'mirrorless', 'professional', 'photography', 'electronics'],
    specifications: { Sensor: '61MP Full-Frame Exmor RS', Video: '8K 30p', AFPoints: '759 phase-detection', IBIS: '5-axis', Viewfinder: '9.44M-dot OLED'},
  },
  {
    id: '46',
    name: 'NextGen Gaming Console X',
    description: 'Powerful next-generation gaming console for immersive experiences.',
    longDescription: 'Experience the future of gaming with the NextGen Console X. Lightning-fast load times, stunning 4K graphics at 120fps, and a vast library of exclusive games. Includes innovative haptic feedback controller.',
    price: 499.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'gaming console nextgen',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'GameSphere',
    rating: 4.8,
    reviewsCount: 600,
    stock: 50,
    tags: ['gaming', 'console', 'nextgen', 'entertainment', 'electronics'],
    specifications: { Resolution: 'Up to 8K', Framerate: 'Up to 120fps', Storage: '1TB Custom NVMe SSD', Controller: 'Haptic Feedback, Adaptive Triggers'},
  },
  {
    id: '47',
    name: 'Mechanical Gaming Keyboard RGB',
    description: 'RGB backlit mechanical keyboard with customizable switches.',
    longDescription: 'Elevate your gaming setup with this RGB mechanical keyboard. Features durable mechanical switches (choice of Red, Blue, Brown), customizable per-key RGB lighting, and a dedicated media control wheel. Aircraft-grade aluminum frame.',
    price: 129.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'keyboard gaming mechanical',
    images: ['https://placehold.co/600x600.png'],
    category: 'Electronics',
    brand: 'ClickMaster',
    rating: 4.7,
    reviewsCount: 180,
    stock: 70,
    tags: ['computer accessories', 'keyboard', 'gaming', 'mechanical', 'rgb', 'electronics'],
    specifications: { SwitchType: 'Mechanical (Red/Blue/Brown options)', Backlighting: 'Per-key RGB', Connectivity: 'USB-C Wired', Material: 'Aluminum Frame'},
  },

  // Existing Fashion
  {
    id: '5',
    name: 'Men\'s Classic Leather Wallet',
    description: 'Genuine leather wallet with multiple compartments.',
    longDescription: 'A timeless accessory, this classic wallet is crafted from genuine leather. It features multiple card slots, a bill compartment, and an ID window. Slim and durable design.',
    price: 45.00,
    originalPrice: 55.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'leather wallet men',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'GentStyle',
    rating: 4.7,
    reviewsCount: 150,
    stock: 200,
    tags: ['men\'s wear', 'accessories', 'wallet', 'leather', 'fashion'],
    specifications: { Material: 'Genuine Leather', Color: 'Black', CardSlots: '8', IDWindow: 'Yes'},
  },
  {
    id: '10',
    name: 'Women\'s Summer Dress (Floral)',
    description: 'Light and airy floral print summer dress.',
    longDescription: 'Stay cool and stylish this summer with our beautiful floral print dress. Made from lightweight cotton, it features a flattering A-line silhouette and adjustable straps. Perfect for casual outings or beach days.',
    price: 35.99,
    originalPrice: 49.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'dress fashion women',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'ChicStyle',
    rating: 4.5,
    reviewsCount: 60,
    stock: 90,
    tags: ['women\'s wear', 'dress', 'summer', 'floral', 'fashion'],
    specifications: { Material: '100% Cotton', Print: 'Floral', Fit: 'A-line', Care: 'Machine washable'},
  },
  {
    id: '11',
    name: 'Men\'s Casual Sneakers',
    description: 'Comfortable and stylish sneakers for everyday wear.',
    longDescription: 'Step out in style with these versatile casual sneakers. Featuring a breathable canvas upper, cushioned insole, and durable rubber outsole. Perfect for pairing with jeans or shorts.',
    price: 59.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'sneakers fashion men',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'UrbanStep',
    rating: 4.3,
    reviewsCount: 110,
    stock: 120,
    tags: ['footwear', 'men\'s wear', 'sneakers', 'casual', 'fashion'],
    specifications: { UpperMaterial: 'Canvas', Sole: 'Rubber', Closure: 'Lace-up', Color: 'Navy Blue'},
  },
  {
    id: '21',
    name: 'Men\'s Running Shoes',
    description: 'Lightweight and breathable running shoes for men.',
    longDescription: 'Achieve your personal best with these lightweight running shoes. Designed for comfort and performance, they feature a breathable mesh upper, responsive cushioning, and durable outsole for excellent traction.',
    price: 89.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'running shoes men',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'RunFlex',
    rating: 4.6,
    reviewsCount: 130,
    stock: 100,
    tags: ['footwear', 'men\'s wear', 'sportswear', 'running shoes', 'fashion'],
    specifications: { Type: 'Neutral', Weight: '250g (Size 9)', Drop: '8mm', Use: 'Road Running'},
  },
  {
    id: '27',
    name: 'Women\'s Elegant Evening Gown',
    description: 'Stunning floor-length evening gown for special occasions.',
    longDescription: 'Make a grand entrance with this elegant evening gown. Crafted from luxurious satin, it features a flattering silhouette, intricate beadwork, and a subtle train. Perfect for galas, weddings, or formal events.',
    price: 299.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'gown fashion women',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'Elegance Couture',
    rating: 4.8,
    reviewsCount: 45,
    stock: 30,
    tags: ['women\'s wear', 'evening gown', 'formal wear', 'dress', 'fashion'],
    specifications: { Material: 'Satin, Beading', Length: 'Floor-length', Color: 'Midnight Blue', Sizes: 'XS, S, M, L, XL'},
  },
  {
    id: '33',
    name: 'Luxury Leather Handbag',
    description: 'Chic and spacious leather handbag for women.',
    longDescription: 'This luxury handbag is crafted from premium Italian leather, offering both style and durability. It features a spacious interior, multiple pockets, and elegant gold-tone hardware. A timeless piece for any wardrobe.',
    price: 349.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'handbag leather fashion',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'BellaDonna',
    rating: 4.7,
    reviewsCount: 80,
    stock: 40,
    tags: ['bags & luggage', 'women\'s wear', 'handbag', 'leather', 'accessories', 'luxury', 'fashion'],
    specifications: { Material: 'Italian Leather', Color: 'Cognac', Dimensions: '12" H x 15" W x 6" D', Hardware: 'Gold-tone'},
  },
  // New Fashion
  {
    id: '48',
    name: 'Men\'s Slim Fit Chinos',
    description: 'Versatile slim fit chinos for smart-casual look.',
    longDescription: 'Crafted from comfortable stretch cotton, these slim fit chinos are a wardrobe staple. Perfect for both office and weekend wear, they offer a modern silhouette and all-day comfort.',
    price: 49.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'chinos pants men',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'ModernMan',
    rating: 4.5,
    reviewsCount: 120,
    stock: 150,
    tags: ['men\'s wear', 'pants', 'chinos', 'smart casual', 'fashion'],
    specifications: { Material: '98% Cotton, 2% Elastane', Fit: 'Slim', Colors: 'Khaki, Navy, Grey'},
  },
  {
    id: '49',
    name: 'Women\'s Knit Cardigan',
    description: 'Cozy knit cardigan, perfect for layering.',
    longDescription: 'This soft knit cardigan is an essential layering piece for cooler weather. It features an open front, long sleeves, and a relaxed fit. Available in various colors to match any outfit.',
    price: 39.50,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'cardigan women knit',
    images: ['https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'CozyKnits',
    rating: 4.6,
    reviewsCount: 95,
    stock: 110,
    tags: ['women\'s wear', 'cardigan', 'knitwear', 'sweater', 'fashion'],
    specifications: { Material: 'Acrylic Blend', Style: 'Open Front', Sleeves: 'Long', Sizes: 'S, M, L, XL'},
  },
  {
    id: '50',
    name: 'Kids\' Graphic Tee (Dinosaur Print)',
    description: 'Fun and comfortable graphic t-shirt for kids.',
    longDescription: 'Let your little one roar in style with this adorable dinosaur print t-shirt. Made from soft, breathable cotton, it\'s perfect for everyday play and adventures. Durable and easy to wash.',
    price: 15.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'kids t-shirt dinosaur',
    images: ['https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'TinyExplorer',
    rating: 4.8,
    reviewsCount: 70,
    stock: 200,
    tags: ['kids\' wear', 't-shirt', 'graphic tee', 'children', 'fashion'],
    specifications: { Material: '100% Cotton', Print: 'Dinosaur Graphic', AgeGroup: '2-8 years'},
  },
  {
    id: '51',
    name: 'Unisex Leather Ankle Boots',
    description: 'Stylish and durable leather ankle boots for all seasons.',
    longDescription: 'These versatile ankle boots are crafted from genuine leather and feature a rugged yet refined design. With a comfortable cushioned insole and slip-resistant outsole, they are perfect for everyday wear.',
    price: 119.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'boots leather footwear',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'UrbanTrekker',
    rating: 4.7,
    reviewsCount: 150,
    stock: 80,
    tags: ['footwear', 'boots', 'leather', 'unisex', 'fashion'],
    specifications: { Material: 'Genuine Leather', Sole: 'Rubber', Closure: 'Lace-up/Side Zip', Colors: 'Black, Brown'},
  },
  {
    id: '52',
    name: 'Classic Chronograph Watch',
    description: 'Elegant chronograph watch with stainless steel bracelet.',
    longDescription: 'A sophisticated timepiece for any occasion. This classic chronograph watch features a precise quartz movement, a durable stainless steel case and bracelet, and a striking blue dial. Water-resistant up to 50m.',
    price: 189.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'watch chronograph steel',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion',
    brand: 'TimelessPieces',
    rating: 4.6,
    reviewsCount: 110,
    stock: 60,
    tags: ['watches', 'chronograph', 'accessories', 'men\'s wear', 'women\'s wear', 'fashion'],
    specifications: { Movement: 'Quartz Chronograph', CaseMaterial: 'Stainless Steel', WaterResistance: '5 ATM', DialColor: 'Blue'},
  },
  {
    id: '53',
    name: 'Expandable Hardshell Luggage Set (3-Piece)',
    description: 'Durable and lightweight hardshell luggage set for all your travels.',
    longDescription: 'Travel with confidence with this 3-piece hardshell luggage set. Includes carry-on, medium, and large suitcases, all featuring expandable capacity, 360-degree spinner wheels, and TSA-approved locks. Scratch-resistant ABS material.',
    price: 199.00,
    originalPrice: 249.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'luggage set travel',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Fashion', // Also Travel
    brand: 'VoyagerElite',
    rating: 4.5,
    reviewsCount: 200,
    stock: 70,
    tags: ['bags & luggage', 'travel', 'suitcases', 'hardshell', 'fashion'],
    specifications: { Material: 'ABS Hardshell', SetIncludes: 'Carry-on, Medium, Large', Wheels: '360° Spinner', Lock: 'TSA-Approved'},
  },

  // Existing Home & Decor
  {
    id: '13',
    name: 'Modern Bookshelf',
    description: 'Stylish and sturdy 5-tier bookshelf for your home.',
    longDescription: 'Organize your books and display your favorite decor items with this modern 5-tier bookshelf. Made from durable engineered wood with a sleek finish, it adds a touch of elegance to any room.',
    price: 89.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'bookshelf furniture decor',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'DecorHome',
    rating: 4.4,
    reviewsCount: 55,
    stock: 40,
    tags: ['furniture', 'bookshelf', 'home decor', 'storage'],
    specifications: { Material: 'Engineered Wood', Tiers: '5', Dimensions: '70" H x 30" W x 12" D', Assembly: 'Required'},
  },
  {
    id: '14',
    name: 'Decorative Throw Pillows (Set of 2)',
    description: 'Soft and stylish throw pillows to accent your sofa or bed.',
    longDescription: 'Add a cozy and decorative touch to your living space with this set of two throw pillows. Featuring a chic geometric pattern and plush filling, they provide both comfort and style. Covers are removable and washable.',
    price: 29.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'pillows decor home',
    images: ['https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'CozyLiving',
    rating: 4.6,
    reviewsCount: 90,
    stock: 75,
    tags: ['home decor', 'pillows', 'cushions', 'textiles'],
    specifications: { SetIncludes: '2 Pillows', Size: '18" x 18"', CoverMaterial: 'Polyester Blend', Filling: 'Hypoallergenic Polyester'},
  },
  {
    id: '22',
    name: 'Ceramic Dinnerware Set (16-Piece)',
    description: 'Elegant ceramic dinnerware set for 4 people.',
    longDescription: 'Elevate your dining experience with this beautiful 16-piece ceramic dinnerware set. Includes dinner plates, salad plates, bowls, and mugs for four. Microwave and dishwasher safe. Available in multiple colors.',
    price: 79.95,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'dinnerware set ceramic',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'TableJoy',
    rating: 4.7,
    reviewsCount: 95,
    stock: 50,
    tags: ['kitchen & dining', 'dinnerware', 'home decor', 'ceramics'],
    specifications: { Material: 'Ceramic', Pieces: '16 (4 place settings)', DishwasherSafe: 'Yes', MicrowaveSafe: 'Yes'},
  },
  {
    id: '29',
    name: 'Luxury Egyptian Cotton Bed Sheet Set',
    description: 'Silky soft 800 thread count Egyptian cotton bed sheets.',
    longDescription: 'Experience ultimate comfort with our luxury Egyptian cotton bed sheet set. Made from 100% long-staple Egyptian cotton with an 800 thread count for a silky smooth feel. Set includes flat sheet, fitted sheet, and two pillowcases.',
    price: 149.99,
    originalPrice: 199.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'bed sheets luxury cotton',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'RoyalLinens',
    rating: 4.9,
    reviewsCount: 220,
    stock: 60,
    tags: ['bedding', 'home decor', 'luxury', 'cotton', 'sheets'],
    specifications: { Material: '100% Egyptian Cotton', ThreadCount: '800', SetIncludes: 'Flat sheet, Fitted sheet, 2 Pillowcases', Size: 'Queen/King'},
  },
  // New Home & Decor
  {
    id: '54',
    name: 'Velvet Accent Chair',
    description: 'Luxurious velvet accent chair with gold metal legs.',
    longDescription: 'Add a touch of glamour to your living room or bedroom with this chic velvet accent chair. It features soft velvet upholstery, a comfortable cushioned seat, and stylish gold-tone metal legs. Available in multiple rich colors.',
    price: 189.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'chair furniture velvet',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'OpulentLiving',
    rating: 4.7,
    reviewsCount: 75,
    stock: 30,
    tags: ['furniture', 'chair', 'accent chair', 'velvet', 'home decor'],
    specifications: { Upholstery: 'Velvet', Frame: 'Wood', Legs: 'Gold-tone Metal', Dimensions: '30" H x 28" W x 29" D'},
  },
  {
    id: '55',
    name: 'Wall Art Canvas Print (Abstract)',
    description: 'Modern abstract canvas print to enhance your wall decor.',
    longDescription: 'This vibrant abstract canvas print adds a contemporary touch to any room. High-quality giclee print on gallery-wrapped canvas, ready to hang. Multiple sizes available.',
    price: 69.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'wall art abstract canvas',
    images: ['https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'ArtScapes',
    rating: 4.6,
    reviewsCount: 110,
    stock: 90,
    tags: ['home decor', 'wall art', 'canvas print', 'abstract art'],
    specifications: { Type: 'Giclee Canvas Print', Style: 'Abstract', Frame: 'Gallery Wrapped', Sizes: 'Various'},
  },
  {
    id: '56',
    name: 'Stainless Steel Cookware Set (10-Piece)',
    description: 'Durable and versatile stainless steel cookware set.',
    longDescription: 'Equip your kitchen with this professional-quality 10-piece stainless steel cookware set. Includes frying pans, saucepans, and a stockpot, all with tri-ply construction for even heating. Oven and dishwasher safe.',
    price: 249.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'cookware set kitchen',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'ChefPro',
    rating: 4.8,
    reviewsCount: 130,
    stock: 40,
    tags: ['kitchen & dining', 'cookware', 'pots and pans', 'stainless steel'],
    specifications: { Material: 'Stainless Steel (Tri-Ply)', Pieces: '10', OvenSafe: 'Up to 500°F', DishwasherSafe: 'Yes'},
  },
  {
    id: '57',
    name: 'Plush Microfiber Bath Towel Set (4-Piece)',
    description: 'Ultra-soft and absorbent microfiber bath towel set.',
    longDescription: 'Wrap yourself in luxury with this plush microfiber bath towel set. Includes four bath towels that are incredibly soft, highly absorbent, and quick-drying. Fade-resistant and durable.',
    price: 34.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'towels bath microfiber',
    images: ['https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'SoftTouch Linens',
    rating: 4.7,
    reviewsCount: 160,
    stock: 100,
    tags: ['bath', 'towels', 'microfiber', 'bathroom accessories'],
    specifications: { Material: 'Microfiber', SetIncludes: '4 Bath Towels', Size: '30" x 56"', Absorbency: 'High'},
  },
  {
    id: '58',
    name: 'Stackable Storage Bins with Lids (Set of 3)',
    description: 'Versatile stackable storage bins for organizing your home.',
    longDescription: 'Declutter your space with this set of three stackable storage bins. Made from durable clear plastic with secure lids, they are perfect for organizing closets, pantries, or offices. See-through design makes it easy to find items.',
    price: 25.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'storage bins organization',
    images: ['https://placehold.co/600x600.png'],
    category: 'Home & Decor',
    brand: 'OrganizeIt',
    rating: 4.5,
    reviewsCount: 85,
    stock: 120,
    tags: ['home storage', 'organization', 'bins', 'containers'],
    specifications: { Material: 'Clear Plastic', SetIncludes: '3 Bins with Lids', Stackable: 'Yes', Size: 'Medium'},
  },
  
  // Existing Appliances
  {
    id: '4',
    name: 'Espresso Coffee Machine',
    description: 'Barista-quality espresso at home.',
    longDescription: 'Start your day right with the perfect espresso. This machine features a 15-bar pressure pump, milk frother, and easy-to-use controls. Durable stainless steel construction.',
    price: 199.50,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'coffee machine kitchen',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'CafeHome',
    rating: 4.3,
    reviewsCount: 75,
    stock: 60,
    tags: ['coffee maker', 'kitchen', 'appliances', 'home appliances'],
    specifications: { PumpPressure: '15 Bar', Material: 'Stainless Steel', MilkFrother: 'Yes', WaterTank: '1.5L'},
  },
  {
    id: '15',
    name: 'Robot Vacuum Cleaner',
    description: 'Smart robot vacuum with mapping and app control.',
    longDescription: 'Keep your floors clean effortlessly with this smart robot vacuum cleaner. It features intelligent mapping, powerful suction, and can be controlled via a smartphone app or voice commands. Works on hard floors and carpets.',
    price: 279.00,
    originalPrice: 329.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'robot vacuum smart',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'CleanBot',
    rating: 4.5,
    reviewsCount: 115,
    stock: 35,
    tags: ['vacuum cleaner', 'robot vacuum', 'smart home', 'appliances', 'home appliances'],
    specifications: { Navigation: 'LIDAR Mapping', SuctionPower: '2500Pa', AppControl: 'Yes', BatteryLife: '120 minutes'},
  },
  {
    id: '16',
    name: 'Air Fryer XL',
    description: 'Large capacity air fryer for healthy, crispy meals.',
    longDescription: 'Enjoy your favorite fried foods with less oil using the Air Fryer XL. Its large 5.8-quart capacity is perfect for families. Features multiple cooking presets, digital touch screen, and easy-to-clean non-stick basket.',
    price: 99.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'air fryer kitchen',
    images: ['https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'KitchenPro',
    rating: 4.7,
    reviewsCount: 180,
    stock: 60,
    tags: ['air fryer', 'kitchen', 'cooking', 'healthy eating', 'appliances', 'home appliances'],
    specifications: { Capacity: '5.8 Quarts', Power: '1700W', Presets: '8 cooking modes', Control: 'Digital Touch Screen'},
  },
  {
    id: '23',
    name: 'Blender Pro',
    description: 'High-speed blender for smoothies and soups.',
    longDescription: 'Create delicious smoothies, soups, and sauces with the Blender Pro. Its powerful motor and stainless steel blades can handle tough ingredients with ease. Features multiple speed settings and a large capacity jar.',
    price: 129.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'blender kitchen appliance',
    images: ['https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'BlendMaster',
    rating: 4.4,
    reviewsCount: 110,
    stock: 40,
    tags: ['blender', 'kitchen', 'appliances', 'smoothies', 'home appliances'],
    specifications: { Power: '1200W', JarCapacity: '64 oz', Blades: 'Stainless Steel', Speeds: 'Variable + Pulse'},
  },
  {
    id: '30',
    name: 'High-Efficiency Washing Machine',
    description: 'Front-load washing machine with multiple wash cycles and steam.',
    longDescription: 'Upgrade your laundry routine with this high-efficiency front-load washing machine. It offers a large capacity, various wash cycles including a steam option for sanitization, and quiet operation. Energy Star certified.',
    price: 699.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'washing machine appliance',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'HomeCleanse',
    rating: 4.6,
    reviewsCount: 90,
    stock: 20,
    tags: ['washing machines', 'laundry', 'appliances', 'home appliances', 'energy efficient'],
    specifications: { Type: 'Front-Load', Capacity: '5.0 cu. ft.', Cycles: '12 (including Steam)', EnergyStar: 'Yes'},
  },
  {
    id: '34',
    name: 'Compact Refrigerator (3.2 Cu. Ft.)',
    description: 'Space-saving compact refrigerator, ideal for dorms or offices.',
    longDescription: 'This compact refrigerator offers 3.2 cubic feet of storage space, perfect for small apartments, dorm rooms, or offices. It features an adjustable thermostat, a separate chiller compartment, and a reversible door.',
    price: 159.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'refrigerator compact appliance',
    images: ['https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'CoolZone',
    rating: 4.3,
    reviewsCount: 60,
    stock: 50,
    tags: ['refrigerators', 'compact', 'appliances', 'home appliances', 'dorm'],
    specifications: { Capacity: '3.2 Cu. Ft.', Type: 'Compact', ChillerCompartment: 'Yes', ReversibleDoor: 'Yes'},
  },
  // New Appliances
  {
    id: '59',
    name: 'Smart French Door Refrigerator',
    description: 'Large capacity smart refrigerator with touch screen and ice maker.',
    longDescription: 'This smart French door refrigerator features a 28 cu. ft. capacity, a built-in touch screen for recipes and notes, and an internal ice and water dispenser. Wi-Fi connected for smart home integration.',
    price: 2499.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'refrigerator smart frenchdoor',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'FridgeTech',
    rating: 4.8,
    reviewsCount: 120,
    stock: 15,
    tags: ['refrigerators', 'smart home', 'french door', 'kitchen', 'appliances'],
    specifications: { Capacity: '28 Cu. Ft.', Type: 'French Door', SmartFeatures: 'Touch Screen, Wi-Fi', IceMaker: 'Internal'},
  },
  {
    id: '60',
    name: 'Portable Air Conditioner (10,000 BTU)',
    description: 'Powerful portable air conditioner for rooms up to 300 sq ft.',
    longDescription: 'Stay cool anywhere with this 10,000 BTU portable air conditioner. Features include a remote control, programmable timer, and dehumidifier mode. Easy to install and move with caster wheels.',
    price: 349.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'air conditioner portable',
    images: ['https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'CoolBreeze',
    rating: 4.5,
    reviewsCount: 90,
    stock: 30,
    tags: ['air conditioners', 'portable ac', 'cooling', 'appliances'],
    specifications: { BTU: '10,000', Coverage: 'Up to 300 sq ft', Modes: 'Cool, Fan, Dehumidify', RemoteControl: 'Yes'},
  },
  {
    id: '61',
    name: 'Countertop Microwave Oven (1.1 Cu. Ft.)',
    description: 'Compact and efficient countertop microwave oven with presets.',
    longDescription: 'This 1.1 cu. ft. countertop microwave offers 1000W of power and multiple cooking presets for quick and easy meals. Features a sleek stainless steel design and an easy-to-read LED display.',
    price: 89.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'microwave oven kitchen',
    images: ['https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'QuickHeat',
    rating: 4.4,
    reviewsCount: 150,
    stock: 60,
    tags: ['microwaves', 'kitchen', 'cooking', 'appliances'],
    specifications: { Capacity: '1.1 Cu. Ft.', Power: '1000W', Presets: '6 Auto-Cook Menus', Turntable: 'Glass'},
  },
  {
    id: '62',
    name: 'Stainless Steel Dishwasher',
    description: 'Quiet and efficient dishwasher with multiple wash cycles.',
    longDescription: 'This built-in stainless steel dishwasher offers powerful cleaning performance with minimal noise. Features multiple wash cycles, a sanitize option, and adjustable racks to accommodate various dish sizes. Energy Star certified.',
    price: 499.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'dishwasher kitchen appliance',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'SparkleClean',
    rating: 4.6,
    reviewsCount: 70,
    stock: 25,
    tags: ['dishwasher', 'kitchen', 'cleaning', 'appliances', 'energy efficient'],
    specifications: { Type: 'Built-in', Material: 'Stainless Steel', NoiseLevel: '48 dBA', Cycles: '5 (including Sanitize)'},
  },
  {
    id: '63',
    name: 'Wall Mount Kitchen Chimney',
    description: 'Stylish wall mount chimney with powerful suction for a smoke-free kitchen.',
    longDescription: 'Keep your kitchen fresh and odor-free with this sleek wall mount chimney. It features powerful suction, baffle filters for easy cleaning, and energy-efficient LED lights. Modern design to complement your kitchen decor.',
    price: 229.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'chimney kitchen appliance',
    images: ['https://placehold.co/600x600.png'],
    category: 'Appliances',
    brand: 'AeroPure',
    rating: 4.5,
    reviewsCount: 55,
    stock: 35,
    tags: ['chimneys', 'kitchen ventilation', 'cooking', 'appliances'],
    specifications: { Type: 'Wall Mount', Suction: '1200 m³/hr', Filters: 'Baffle Filters', Lights: 'LED'},
  },

  // Existing Grocery
  {
    id: '7',
    name: 'Organic Apples (1kg)',
    description: 'Fresh and juicy organic apples, perfect for snacking.',
    longDescription: 'Enjoy the crisp taste of our certified organic apples. Grown without synthetic pesticides or fertilizers, these apples are a healthy and delicious choice for the whole family. Each pack contains approximately 1kg.',
    price: 4.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'apples grocery',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'FarmFresh',
    rating: 4.6,
    reviewsCount: 45,
    stock: 150,
    tags: ['fruits & vegetables', 'grocery', 'fruits', 'organic', 'healthy'],
    specifications: { Weight: '1kg (approx)', Type: 'Organic Gala Apples', Origin: 'Local Farms'},
  },
  {
    id: '8',
    name: 'Whole Wheat Bread Loaf',
    description: 'Nutritious whole wheat bread, freshly baked.',
    longDescription: 'Our whole wheat bread is baked fresh daily using 100% whole grain flour. It\'s a great source of fiber and perfect for sandwiches or toast. No artificial preservatives.',
    price: 3.50,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'bread grocery bakery',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'BakeryLane',
    rating: 4.4,
    reviewsCount: 30,
    stock: 80,
    tags: ['dairy & bakery', 'grocery', 'bakery', 'bread', 'whole wheat'],
    specifications: { Ingredients: 'Whole wheat flour, water, yeast, salt', Dietary: 'No artificial preservatives'},
  },
  {
    id: '19',
    name: 'Organic Whole Milk (1L)',
    description: 'Fresh, creamy organic whole milk.',
    longDescription: 'Our organic whole milk comes from grass-fed cows and is pasteurized at low temperatures to preserve its natural goodness. Rich in calcium and vitamins, it\'s perfect for drinking, cereal, or cooking. 1 liter carton.',
    price: 2.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'milk carton grocery',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'HappyFarms Dairy',
    rating: 4.7,
    reviewsCount: 88,
    stock: 120,
    tags: ['dairy & bakery', 'grocery', 'dairy', 'milk', 'organic'],
    specifications: { Volume: '1 Liter', Type: 'Organic Whole Milk', FatContent: '3.5%'},
  },
  {
    id: '25',
    name: 'Premium Italian Pasta (500g)',
    description: 'Artisanal Italian pasta made with durum wheat semolina.',
    longDescription: 'Taste the difference with our premium Italian pasta. Made using traditional bronze dies for a rough texture that holds sauces perfectly. Crafted from 100% durum wheat semolina.',
    price: 3.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'pasta grocery italian',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'Bella Cucina',
    rating: 4.8,
    reviewsCount: 70,
    stock: 200,
    tags: ['staples', 'grocery', 'pasta', 'italian', 'food'],
    specifications: { Weight: '500g', Type: 'Spaghetti', Ingredients: 'Durum wheat semolina, water'},
  },
  {
    id: '31',
    name: 'Gourmet Dark Chocolate Bar (70% Cacao)',
    description: 'Rich and intense dark chocolate bar for connoisseurs.',
    longDescription: 'Indulge in the complex flavors of our gourmet dark chocolate bar. Made with 70% single-origin cacao, it offers notes of fruit and spice with a smooth finish. Perfect for pairing or savoring on its own.',
    price: 5.50,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'chocolate grocery gourmet',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'ChocoArtisan',
    rating: 4.9,
    reviewsCount: 120,
    stock: 150,
    tags: ['snacks', 'grocery', 'chocolate', 'dark chocolate', 'gourmet', 'sweets'],
    specifications: { CacaoPercentage: '70%', Weight: '100g', Origin: 'Ecuador', Ingredients: 'Cacao beans, cane sugar, cacao butter'},
  },
  // New Grocery
  {
    id: '64',
    name: 'Fresh Organic Bananas (Bunch)',
    description: 'Naturally ripened organic bananas, rich in potassium.',
    longDescription: 'Our organic bananas are sourced from certified farms and are naturally ripened for optimal flavor and nutrition. A perfect healthy snack or addition to smoothies.',
    price: 2.49,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'bananas fruit organic',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'FarmFresh',
    rating: 4.7,
    reviewsCount: 95,
    stock: 180,
    tags: ['fruits & vegetables', 'grocery', 'fruits', 'organic', 'healthy'],
    specifications: { Quantity: 'Bunch (approx 5-7 bananas)', Type: 'Organic Cavendish', Storage: 'Store at room temperature'},
  },
  {
    id: '65',
    name: 'Artisan Sourdough Bread',
    description: 'Crusty artisan sourdough bread with a tangy flavor.',
    longDescription: 'Handcrafted using traditional methods, our artisan sourdough bread has a delightfully chewy crust and a soft, tangy interior. Perfect for sandwiches, toast, or serving with soups.',
    price: 5.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'sourdough bread bakery',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'ArtisanBakers',
    rating: 4.9,
    reviewsCount: 110,
    stock: 50,
    tags: ['dairy & bakery', 'grocery', 'bakery', 'bread', 'sourdough'],
    specifications: { Ingredients: 'Flour, water, salt, natural starter', Type: 'Artisan Sourdough Loaf'},
  },
  {
    id: '66',
    name: 'Basmati Rice (5kg Bag)',
    description: 'Premium quality long-grain Basmati rice.',
    longDescription: 'This premium Basmati rice is known for its fragrant aroma and fluffy texture when cooked. Aged to perfection, it\'s ideal for biryanis, pilafs, or as a side dish. 5kg value bag.',
    price: 15.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'rice basmati staples',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'RoyalHarvest',
    rating: 4.6,
    reviewsCount: 130,
    stock: 90,
    tags: ['staples', 'grocery', 'rice', 'basmati', 'grains'],
    specifications: { Weight: '5kg', Type: 'Long-Grain Basmati', Aging: 'Min. 12 months'},
  },
  {
    id: '67',
    name: 'Kettle Cooked Potato Chips (Sea Salt)',
    description: 'Crunchy kettle-cooked potato chips with a hint of sea salt.',
    longDescription: 'Indulge in these extra crunchy potato chips, kettle-cooked in small batches for superior flavor and texture. Lightly seasoned with natural sea salt. A satisfying snack anytime.',
    price: 3.29,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'potato chips snack',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'CrunchTime Snacks',
    rating: 4.5,
    reviewsCount: 105,
    stock: 150,
    tags: ['snacks', 'grocery', 'chips', 'potato chips', 'salty snacks'],
    specifications: { Flavor: 'Sea Salt', Type: 'Kettle Cooked', NetWeight: '150g'},
  },
  {
    id: '68',
    name: 'Cold Pressed Orange Juice (1L)',
    description: '100% pure cold-pressed orange juice, no added sugar.',
    longDescription: 'Enjoy the refreshing taste of pure oranges with our cold-pressed juice. Made from 100% fresh oranges, it retains more vitamins and nutrients. No added sugar, preservatives, or artificial flavors.',
    price: 4.79,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'orange juice beverage',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'PureSip',
    rating: 4.8,
    reviewsCount: 90,
    stock: 100,
    tags: ['beverages', 'grocery', 'juice', 'orange juice', 'cold pressed'],
    specifications: { Volume: '1 Liter', Ingredients: '100% Orange Juice', Process: 'Cold Pressed', SugarAdded: 'No'},
  },
  {
    id: '69',
    name: 'Natural Almond Body Wash (500ml)',
    description: 'Gentle and moisturizing natural body wash with almond oil.',
    longDescription: 'Pamper your skin with this natural body wash enriched with sweet almond oil and vitamin E. It cleanses gently while leaving your skin soft, smooth, and hydrated. Paraben and sulfate-free.',
    price: 8.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'body wash personal care',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'NaturePure',
    rating: 4.7,
    reviewsCount: 75,
    stock: 80,
    tags: ['personal care', 'grocery', 'body wash', 'natural', 'skincare'],
    specifications: { Scent: 'Almond', Volume: '500ml', KeyIngredients: 'Almond Oil, Vitamin E', FreeFrom: 'Parabens, Sulfates'},
  },
  {
    id: '70',
    name: 'Eco-Friendly Dishwashing Liquid (750ml)',
    description: 'Plant-based dishwashing liquid, tough on grease, gentle on hands.',
    longDescription: 'This eco-friendly dishwashing liquid effectively cuts through grease and grime while being biodegradable and gentle on your skin. Made with plant-derived ingredients and a refreshing citrus scent.',
    price: 6.49,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'dish soap household',
    images: ['https://placehold.co/600x600.png'],
    category: 'Grocery',
    brand: 'EcoClean Home',
    rating: 4.6,
    reviewsCount: 60,
    stock: 90,
    tags: ['household', 'grocery', 'cleaning', 'dish soap', 'eco-friendly'],
    specifications: { Scent: 'Citrus', Volume: '750ml', Type: 'Plant-based, Biodegradable'},
  },

  // Existing Travel
  {
    id: '17',
    name: 'Weekend Getaway Package: Mountain Retreat',
    description: '2-night stay for two at a scenic mountain lodge.',
    longDescription: 'Escape to the mountains with this relaxing weekend getaway package. Includes a 2-night stay for two people at a charming lodge, daily breakfast, and access to hiking trails. Enjoy breathtaking views and fresh mountain air.',
    price: 349.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'travel mountain vacation',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Travel',
    brand: 'AdventureEscapes',
    rating: 4.8,
    reviewsCount: 40,
    stock: 10, 
    tags: ['vacation package', 'mountains', 'leisure', 'travel'],
    specifications: { Duration: '2 nights', Includes: 'Accommodation, Breakfast', Location: 'Serene Mountain Valley', Validity: '6 months from purchase'},
  },
  {
    id: '18',
    name: 'City Tour: Historical Landmarks',
    description: 'Guided walking tour of the city\'s most famous historical sites.',
    longDescription: 'Discover the rich history of the city with our expert-guided walking tour. Visit iconic landmarks, learn fascinating stories, and immerse yourself in the local culture. Tour lasts approximately 3 hours.',
    price: 45.00, 
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'travel city tour',
    images: ['https://placehold.co/600x600.png'],
    category: 'Travel',
    brand: 'UrbanExplorers',
    rating: 4.6,
    reviewsCount: 75,
    stock: 50, 
    tags: ['city tour', 'tourism', 'historical', 'guided tour', 'travel'],
    specifications: { Type: 'Walking Tour', Duration: '3 hours', GroupSize: 'Max 15 people', Language: 'English'},
  },
  {
    id: '24',
    name: 'Beach Holiday Package: Tropical Paradise',
    description: '5-night all-inclusive stay at a luxury beach resort.',
    longDescription: 'Indulge in a tropical getaway with this 5-night all-inclusive package. Stay at a stunning beach resort, enjoy gourmet meals, beverages, and various water sports activities. Perfect for a romantic escape or family vacation.',
    price: 1299.00,
    originalPrice: 1599.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'travel beach resort',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Travel',
    brand: 'SunSeeker Vacations',
    rating: 4.9,
    reviewsCount: 65,
    stock: 5,
    tags: ['vacation package', 'beach', 'all-inclusive', 'luxury', 'travel'],
    specifications: { Duration: '5 nights', Includes: 'All meals, drinks, activities', Location: 'Tropical Island Resort', Accommodation: 'Ocean View Suite'},
  },
  {
    id: '35',
    name: 'Adventure Backpack (50L)',
    description: 'Durable and versatile backpack for hiking and travel.',
    longDescription: 'Embark on your next adventure with this 50L backpack. Made from water-resistant nylon, it features multiple compartments, adjustable straps, a comfortable padded back panel, and an integrated rain cover. Perfect for multi-day hikes or backpacking trips.',
    price: 75.00,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'backpack travel hiking',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Travel', 
    brand: 'TrailBlazer Gear',
    rating: 4.6,
    reviewsCount: 140,
    stock: 90,
    tags: ['backpacks', 'hiking', 'outdoors', 'gear', 'travel'],
    specifications: { Capacity: '50 Liters', Material: 'Water-resistant Nylon', RainCover: 'Integrated', Compartments: 'Multiple'},
  },
  // New Travel
  {
    id: '71',
    name: 'Lightweight Carry-On Spinner Luggage',
    description: 'Durable and lightweight carry-on suitcase with spinner wheels.',
    longDescription: 'Travel light and smart with this carry-on spinner luggage. Constructed from durable polycarbonate, it meets most airline size restrictions and features smooth spinner wheels for easy maneuverability. Includes TSA lock.',
    price: 89.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'luggage carry-on travel',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Travel',
    brand: 'AeroLite',
    rating: 4.7,
    reviewsCount: 180,
    stock: 100,
    tags: ['luggage', 'carry-on', 'suitcase', 'travel gear'],
    specifications: { Material: 'Polycarbonate', Size: '20 inch (Carry-on)', Wheels: '4 Spinner Wheels', Lock: 'TSA Approved'},
  },
  {
    id: '72',
    name: 'Travel Neck Pillow (Memory Foam)',
    description: 'Ergonomic memory foam neck pillow for comfortable travel.',
    longDescription: 'Ensure a comfortable journey with this ergonomic memory foam neck pillow. It provides excellent support for your neck and head, helping to prevent stiffness during long flights or car rides. Includes a washable cover.',
    price: 19.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'neck pillow travel comfort',
    images: ['https://placehold.co/600x600.png'],
    category: 'Travel',
    brand: 'ComfyJourney',
    rating: 4.8,
    reviewsCount: 250,
    stock: 150,
    tags: ['travel accessories', 'neck pillow', 'comfort', 'memory foam'],
    specifications: { Material: 'Memory Foam, Velvet Cover', Shape: 'U-Shaped', WashableCover: 'Yes'},
  },
  {
    id: '73',
    name: 'Universal Travel Adapter',
    description: 'All-in-one universal travel adapter for worldwide use.',
    longDescription: 'Stay powered up wherever you go with this universal travel adapter. Compatible with outlets in over 150 countries, it features multiple USB ports for charging several devices simultaneously. Compact and safe design.',
    price: 24.95,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'travel adapter universal',
    images: ['https://placehold.co/600x600.png'],
    category: 'Travel',
    brand: 'PowerLink Global',
    rating: 4.6,
    reviewsCount: 190,
    stock: 120,
    tags: ['travel electronics', 'travel adapter', 'charger', 'gadgets'],
    specifications: { Compatibility: 'US/EU/UK/AU Plugs', USBPorts: '4 (3 USB-A, 1 USB-C)', SafetyFeatures: 'Surge Protection, Overload Fuse'},
  },
  // Sports & Outdoors (existing, not explicitly requested to expand but good for variety)
   {
    id: '6',
    name: 'Yoga Mat Premium',
    description: 'Eco-friendly, non-slip yoga mat for all practices.',
    longDescription: 'Enhance your yoga practice with this premium, eco-friendly mat. Made from natural tree rubber, it offers excellent grip and cushioning. Lightweight and easy to carry.',
    price: 39.99,
    imageUrl: 'https://placehold.co/300x300.png',
    dataAiHint: 'yoga mat fitness',
    images: ['https://placehold.co/600x600.png'],
    category: 'Sports & Outdoors',
    brand: 'ZenFlow',
    rating: 4.9,
    reviewsCount: 300,
    stock: 120,
    tags: ['yoga', 'fitness', 'sports'],
    specifications: { Material: 'Natural Tree Rubber', Thickness: '5mm', Dimensions: '72" x 24"', EcoFriendly: 'Yes'},
  },
];

export const mockReviews: Review[] = [
  { id: 'r1', productId: '1', author: 'John D.', rating: 5, comment: 'Amazing phone, super fast and great camera!', date: '2023-10-01' },
  { id: 'r2', productId: '1', author: 'Jane S.', rating: 4, comment: 'Good phone, battery could be slightly better.', date: '2023-10-05' },
  { id: 'r3', productId: '2', author: 'Mike B.', rating: 5, comment: 'Best headphones I have ever owned. Noise cancellation is superb.', date: '2023-09-15' },
  { id: 'r4', productId: '2', author: 'Lisa K.', rating: 4, comment: 'Very comfortable and great sound, a bit pricey though.', date: '2023-09-20' },
  { id: 'r5', productId: '7', author: 'Sarah P.', rating: 5, comment: 'These apples are delicious and so fresh!', date: '2023-11-01' },
  { id: 'r6', productId: '8', author: 'Tom W.', rating: 4, comment: 'Good solid bread, makes great toast.', date: '2023-11-02' },
  { id: 'r7', productId: '9', author: 'Emily R.', rating: 4, comment: 'Great value for the price, does everything I need.', date: '2023-10-20' },
  { id: 'r8', productId: '10', author: 'Jessica L.', rating: 5, comment: 'Love this dress! Perfect for summer.', date: '2023-07-10' },
  { id: 'r9', productId: '12', author: 'Kevin G.', rating: 5, comment: 'Absolute beast of a laptop. Runs everything smoothly.', date: '2023-10-25' },
  { id: 'r10', productId: '15', author: 'Maria C.', rating: 4, comment: 'Robot vacuum is a lifesaver. Cleans pretty well.', date: '2023-09-30' },
  { id: 'r11', productId: '17', author: 'David K.', rating: 5, comment: 'The mountain retreat was fantastic. So peaceful.', date: '2023-08-15' },
  { id: 'r12', productId: '19', author: 'Laura B.', rating: 5, comment: 'Creamy and delicious milk, my kids love it!', date: '2023-11-05' },
  { id: 'r13', productId: '20', author: 'Chris P.', rating: 4, comment: 'Great sound for its size. Battery life is decent.', date: '2023-10-15' },
  { id: 'r14', productId: '26', author: 'Sam K.', rating: 5, comment: 'This phone is incredible! The camera is out of this world.', date: '2023-11-10'},
  { id: 'r15', productId: '28', author: 'Olivia M.', rating: 4, comment: 'Love my new smartwatch, tracks everything accurately.', date: '2023-11-08'},
  { id: 'r16', productId: '32', author: 'Robert H.', rating: 5, comment: 'Amazing camera quality, the lens is superb.', date: '2023-10-30'},
  { id: 'r17', productId: '36', author: 'Alice W.', rating: 5, comment: 'The new iFruit Phone is a game changer! So smooth.', date: '2023-11-12' },
  { id: 'r18', productId: '37', author: 'Bob C.', rating: 4, comment: 'Pixel Perfect 9 camera is truly smart. Great photos.', date: '2023-11-11' },
  { id: 'r19', productId: '42', author: 'Charlie E.', rating: 5, comment: 'UltraBook Slim Pro is perfect for my work travels.', date: '2023-11-09' },
  { id: 'r20', productId: '46', author: 'Diana F.', rating: 5, comment: 'NextGen Gaming Console X is mind-blowing! The graphics are insane.', date: '2023-11-14' },
  { id: 'r21', productId: '54', author: 'Ethan G.', rating: 4, comment: 'Velvet accent chair looks stunning in my living room.', date: '2023-11-07' },
  { id: 'r22', productId: '59', author: 'Fiona H.', rating: 5, comment: 'This smart fridge is amazing! Love the touch screen.', date: '2023-11-13' },
  { id: 'r23', productId: '64', author: 'George I.', rating: 5, comment: 'Best organic bananas I\'ve had. So sweet!', date: '2023-11-06' },
  { id: 'r24', productId: '71', author: 'Hannah J.', rating: 4, comment: 'Lightweight carry-on, perfect for short trips.', date: '2023-11-05' },
];

export function getAllProducts(): Product[] {
  return mockProducts;
}

export function getProductById(id: string): Product | undefined {
  return mockProducts.find(product => product.id === id);
}

export function getReviewsByProductId(productId: string): Review[] {
  return mockReviews.filter(review => review.productId === productId);
}
